[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables - set these in Netlify dashboard:
# NEXTAUTH_URL = "https://isaacavazquez.com"
# NEXTAUTH_SECRET = "kr1TsL7jO3hm21vnJSze8tCWMLVBPxA6VQCbFK4ywqw="
# ADMIN_USERNAME = "admin"
# ADMIN_PASSWORD = "admin123"
# FANTASYPROS_USERNAME = "Votedonut@yahoo.com"
# FANTASYPROS_PASSWORD = "n5WRvVzc^KyDi2k^"
# CRON_SECRET = "6442c98c509eb7c8b62852d6efb084e8699e46b6f66955f66784cae784c64176"
