// ---------------------------------------------------------------------------
// Job search tracker – company registry. Public boards get polled; manual
// cards link to the portal's full-time business search instead.
// ---------------------------------------------------------------------------

import type { MBACompany } from "@/types/mba-jobs";

const MBA_CATEGORY_COLORS = {
  fintech: "color-mix(in srgb, var(--c97-positive) 62%, var(--c97-ink) 38%)",
  startup: "color-mix(in srgb, var(--c97-accent) 34%, var(--c97-ink) 66%)",
  "big-tech": "color-mix(in srgb, var(--c97-ink) 68%, var(--c97-rule) 32%)",
} as const;

export const MBA_COMPANIES: MBACompany[] = [
  // ── Fintech (public feeds + manual fallbacks) ─────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    atsType: "greenhouse",
    sourceKey: "stripe",
    category: "fintech",
    careersUrl: "https://stripe.com/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "ST",
  },
  {
    id: "brex",
    name: "Brex",
    atsType: "greenhouse",
    sourceKey: "brex",
    category: "fintech",
    careersUrl: "https://www.brex.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "BR",
  },
  {
    id: "plaid",
    name: "Plaid",
    atsType: "ashby",
    sourceKey: "plaid",
    category: "fintech",
    careersUrl: "https://plaid.com/careers",
    jobsUrl: "https://plaid.com/careers/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "PL",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    atsType: "greenhouse",
    sourceKey: "robinhood",
    category: "fintech",
    careersUrl: "https://careers.robinhood.com",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "RH",
  },
  {
    id: "carta",
    name: "Carta",
    atsType: "greenhouse",
    sourceKey: "carta",
    category: "fintech",
    careersUrl: "https://carta.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CA",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    atsType: "greenhouse",
    sourceKey: "coinbase",
    category: "fintech",
    careersUrl: "https://www.coinbase.com/careers",
    jobsUrl: "https://www.coinbase.com/careers/positions",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CB",
  },
  {
    id: "block",
    name: "Block",
    atsType: "greenhouse",
    sourceKey: "block",
    category: "fintech",
    careersUrl: "https://block.xyz/careers/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "BL",
  },
  {
    id: "affirm",
    name: "Affirm",
    atsType: "greenhouse",
    sourceKey: "affirm",
    category: "fintech",
    careersUrl: "https://www.affirm.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "AF",
  },
  {
    id: "chime",
    name: "Chime",
    atsType: "greenhouse",
    sourceKey: "chime",
    category: "fintech",
    careersUrl: "https://careers.chime.com/en/",
    jobsUrl: "https://careers.chime.com/en/jobs/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CH",
  },
  {
    id: "gusto",
    name: "Gusto",
    atsType: "greenhouse",
    sourceKey: "gusto",
    category: "fintech",
    careersUrl: "https://gusto.com/about/careers/join-the-team",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "GU",
  },
  {
    id: "mercury",
    name: "Mercury",
    atsType: "greenhouse",
    sourceKey: "mercury",
    category: "fintech",
    careersUrl: "https://mercury.com/jobs",
    jobsUrl: "https://mercury.com/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "ME",
  },
  {
    id: "ramp",
    name: "Ramp",
    atsType: "ashby",
    sourceKey: "ramp",
    category: "fintech",
    careersUrl: "https://ramp.com/careers/",
    jobsUrl: "https://jobs.ashbyhq.com/ramp",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "RA",
  },
  // Boards below were each verified with one GET to the fetcher's endpoint on 2026-10-07.
  {
    id: "sofi",
    name: "SoFi",
    atsType: "greenhouse",
    sourceKey: "sofi",
    category: "fintech",
    careersUrl: "https://www.sofi.com/careers/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "SF",
  },
  {
    id: "toast",
    name: "Toast",
    atsType: "greenhouse",
    sourceKey: "toast",
    category: "fintech",
    careersUrl: "https://careers.toasttab.com/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "TO",
  },
  {
    id: "betterment",
    name: "Betterment",
    atsType: "greenhouse",
    sourceKey: "betterment",
    category: "fintech",
    careersUrl: "https://www.betterment.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "BE",
  },
  {
    id: "wealthfront",
    name: "Wealthfront",
    atsType: "lever",
    sourceKey: "wealthfront",
    category: "fintech",
    careersUrl: "https://www.wealthfront.com/careers",
    jobsUrl: "https://jobs.lever.co/wealthfront",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "WF",
  },
  {
    id: "upstart",
    name: "Upstart",
    atsType: "greenhouse",
    sourceKey: "upstart",
    category: "fintech",
    careersUrl: "https://careers.upstart.com/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "UP",
  },
  {
    id: "adyen",
    name: "Adyen",
    atsType: "greenhouse",
    sourceKey: "adyen",
    category: "fintech",
    careersUrl: "https://careers.adyen.com/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "AD",
  },
  {
    id: "wise",
    name: "Wise",
    atsType: "smartrecruiters",
    sourceKey: "Wise",
    category: "fintech",
    careersUrl: "https://wise.jobs/",
    jobsUrl: "https://jobs.smartrecruiters.com/Wise",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "WI",
  },
  {
    id: "checkr",
    name: "Checkr",
    atsType: "greenhouse",
    sourceKey: "checkr",
    category: "fintech",
    careersUrl: "https://checkr.com/company/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CK",
  },
  {
    id: "modern-treasury",
    name: "Modern Treasury",
    atsType: "ashby",
    sourceKey: "moderntreasury",
    category: "fintech",
    careersUrl: "https://www.moderntreasury.com/careers",
    jobsUrl: "https://jobs.ashbyhq.com/moderntreasury",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "MT",
  },
  {
    id: "lithic",
    name: "Lithic",
    atsType: "greenhouse",
    sourceKey: "lithic",
    category: "fintech",
    careersUrl: "https://www.lithic.com/about/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "LI",
  },
  {
    id: "navan",
    name: "Navan",
    atsType: "greenhouse",
    sourceKey: "tripactions",
    category: "fintech",
    careersUrl: "https://navan.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "NV",
  },
  {
    id: "acorns",
    name: "Acorns",
    atsType: "ashby",
    sourceKey: "acorns",
    category: "fintech",
    careersUrl: "https://www.acorns.com/careers/",
    jobsUrl: "https://jobs.ashbyhq.com/acorns",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "AC",
  },
  {
    id: "public",
    name: "Public",
    atsType: "greenhouse",
    sourceKey: "public",
    category: "fintech",
    careersUrl: "https://public.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "PU",
  },
  {
    id: "alloy",
    name: "Alloy",
    atsType: "greenhouse",
    sourceKey: "alloy",
    category: "fintech",
    careersUrl: "https://www.alloy.com/about/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "AL",
  },
  {
    id: "melio",
    name: "Melio",
    atsType: "greenhouse",
    sourceKey: "melio",
    category: "fintech",
    careersUrl: "https://www.lifeatmelio.com/",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "ML",
  },
  {
    id: "zip",
    name: "Zip",
    atsType: "ashby",
    sourceKey: "zip",
    category: "fintech",
    careersUrl: "https://zip.com/careers",
    jobsUrl: "https://jobs.ashbyhq.com/zip",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "ZP",
  },
  // ── Startup / Growth (public feeds + manual fallbacks) ────────────────────
  {
    id: "airbnb",
    name: "Airbnb",
    atsType: "greenhouse",
    sourceKey: "airbnb",
    category: "startup",
    careersUrl: "https://careers.airbnb.com",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AB",
  },
  {
    id: "lyft",
    name: "Lyft",
    atsType: "greenhouse",
    sourceKey: "lyft",
    category: "startup",
    careersUrl: "https://www.lyft.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "LY",
  },
  {
    id: "doordash",
    name: "DoorDash",
    atsType: "greenhouse",
    sourceKey: "doordashusa",
    category: "startup",
    careersUrl: "https://careersatdoordash.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DD",
  },
  {
    id: "figma",
    name: "Figma",
    atsType: "greenhouse",
    sourceKey: "figma",
    category: "startup",
    careersUrl: "https://www.figma.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "FG",
  },
  {
    id: "notion",
    name: "Notion",
    atsType: "ashby",
    sourceKey: "notion",
    category: "startup",
    careersUrl: "https://www.notion.so/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "NO",
  },
  {
    id: "airtable",
    name: "Airtable",
    atsType: "greenhouse",
    sourceKey: "airtable",
    category: "startup",
    careersUrl: "https://airtable.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AT",
  },
  {
    id: "rippling",
    name: "Rippling",
    atsType: "manual",
    sourceKey: "rippling",
    category: "startup",
    careersUrl: "https://www.rippling.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "RI",
  },
  {
    id: "asana",
    name: "Asana",
    atsType: "greenhouse",
    sourceKey: "asana",
    category: "startup",
    careersUrl: "https://asana.com/jobs",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AS",
  },
  {
    id: "reddit",
    name: "Reddit",
    atsType: "greenhouse",
    sourceKey: "reddit",
    category: "startup",
    careersUrl: "https://www.redditinc.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "RD",
  },
  {
    id: "datadog",
    name: "Datadog",
    atsType: "greenhouse",
    sourceKey: "datadog",
    category: "startup",
    careersUrl: "https://careers.datadoghq.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DD",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    atsType: "greenhouse",
    sourceKey: "dropbox",
    category: "startup",
    careersUrl: "https://jobs.dropbox.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DB",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    atsType: "greenhouse",
    // The "hubspot" board answers 200 with no postings. The live one is "hubspotjobs".
    sourceKey: "hubspotjobs",
    category: "startup",
    careersUrl: "https://www.hubspot.com/careers/jobs",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "HS",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    atsType: "greenhouse",
    sourceKey: "cloudflare",
    category: "startup",
    careersUrl: "https://www.cloudflare.com/careers/jobs/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "CF",
  },
  {
    id: "openai",
    name: "OpenAI",
    atsType: "ashby",
    sourceKey: "openai",
    category: "startup",
    careersUrl: "https://openai.com/careers/search/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "OA",
  },
  {
    id: "miro",
    name: "Miro",
    atsType: "direct-html",
    sourceKey: "miro",
    category: "startup",
    careersUrl: "https://us.miro.com/careers/open-positions/",
    jobsUrl: "https://us.miro.com/careers/open-positions/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "MI",
  },
  {
    id: "instacart",
    name: "Instacart",
    atsType: "greenhouse",
    sourceKey: "instacart",
    category: "startup",
    careersUrl: "https://www.instacart.careers/current-openings",
    jobsUrl: "https://www.instacart.careers/current-openings",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "IC",
  },
  {
    id: "canva",
    name: "Canva",
    atsType: "smartrecruiters",
    sourceKey: "Canva",
    category: "startup",
    careersUrl: "https://www.lifeatcanva.com/",
    jobsUrl: "https://www.lifeatcanva.com/en/jobs/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "CV",
  },
  {
    id: "discord",
    name: "Discord",
    atsType: "greenhouse",
    sourceKey: "discord",
    category: "startup",
    careersUrl: "https://discord.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DC",
  },
  {
    id: "duolingo",
    name: "Duolingo",
    atsType: "greenhouse",
    sourceKey: "duolingo",
    category: "startup",
    careersUrl: "https://careers.duolingo.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DU",
  },
  // ── Big Tech (mixed public feeds + manual portals) ────────────────────────
  {
    id: "pinterest",
    name: "Pinterest",
    atsType: "greenhouse",
    sourceKey: "pinterest",
    category: "big-tech",
    careersUrl: "https://www.pinterestcareers.com/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "PI",
  },
  {
    id: "roblox",
    name: "Roblox",
    atsType: "greenhouse",
    sourceKey: "roblox",
    category: "big-tech",
    careersUrl: "https://careers.roblox.com/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "RB",
  },
  {
    id: "google",
    name: "Google",
    atsType: "manual",
    sourceKey: "google",
    category: "big-tech",
    careersUrl:
      "https://www.google.com/about/careers/applications/jobs/results/?employment_type=FULL_TIME&category=BUSINESS_STRATEGY",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "GO",
  },
  {
    id: "amazon",
    name: "Amazon",
    atsType: "manual",
    sourceKey: "amazon",
    category: "big-tech",
    careersUrl: "https://www.amazon.jobs/content/en/team-category/mba-opportunities",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AM",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    atsType: "manual",
    sourceKey: "microsoft",
    category: "big-tech",
    careersUrl: "https://apply.careers.microsoft.com/careers?query=mba&et=Full-Time",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "MS",
  },
  {
    id: "meta",
    name: "Meta",
    atsType: "manual",
    sourceKey: "meta",
    category: "big-tech",
    careersUrl: "https://www.metacareers.com/jobsearch/?q=mba&roles%5B0%5D=full-time",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "ME",
  },
  {
    id: "apple",
    name: "Apple",
    atsType: "manual",
    sourceKey: "apple",
    category: "big-tech",
    careersUrl: "https://jobs.apple.com/en-us/search?search=mba&team=corporate-functions-CORP",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AP",
  },
  {
    id: "uber",
    name: "Uber",
    atsType: "manual",
    sourceKey: "uber",
    category: "big-tech",
    careersUrl: "https://www.uber.com/us/en/careers/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "UB",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    // The Lever board answers 404. Postings now sit on iCIMS portals, which no fetcher here reads.
    atsType: "manual",
    sourceKey: "atlassian",
    category: "big-tech",
    careersUrl: "https://www.atlassian.com/company/careers/all-jobs",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AT",
  },
  {
    id: "adobe",
    name: "Adobe",
    atsType: "manual",
    sourceKey: "adobe",
    category: "big-tech",
    careersUrl: "https://careers.adobe.com/us/en",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AD",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    atsType: "manual",
    sourceKey: "salesforce",
    category: "big-tech",
    careersUrl: "https://careers.salesforce.com/en/jobs/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "SF",
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    atsType: "manual",
    sourceKey: "nvidia",
    category: "big-tech",
    careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "NV",
  },
];

export const MBA_COMPANY_MAP = new Map<string, MBACompany>(
  MBA_COMPANIES.map((c) => [c.id, c])
);
