// ---------------------------------------------------------------------------
// MBA Internship Notifications – company registry
// ---------------------------------------------------------------------------

import type { MBACompany } from "@/types/mba-jobs";

const MBA_CATEGORY_COLORS = {
  fintech: "color-mix(in srgb, var(--home-moss) 62%, var(--home-ink) 38%)",
  startup: "color-mix(in srgb, var(--home-acid) 34%, var(--home-ink) 66%)",
  "big-tech": "var(--home-haze)",
} as const;

export const MBA_COMPANIES: MBACompany[] = [
  // ── Fintech (public feeds + manual fallbacks) ─────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    atsType: "greenhouse",
    atsSlug: "stripe",
    category: "fintech",
    careersUrl: "https://stripe.com/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "ST",
  },
  {
    id: "brex",
    name: "Brex",
    atsType: "greenhouse",
    atsSlug: "brex",
    category: "fintech",
    careersUrl: "https://www.brex.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "BR",
  },
  {
    id: "plaid",
    name: "Plaid",
    atsType: "manual",
    atsSlug: "",
    category: "fintech",
    careersUrl: "https://plaid.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "PL",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    atsType: "greenhouse",
    atsSlug: "robinhood",
    category: "fintech",
    careersUrl: "https://careers.robinhood.com",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "RH",
  },
  {
    id: "carta",
    name: "Carta",
    atsType: "greenhouse",
    atsSlug: "carta",
    category: "fintech",
    careersUrl: "https://carta.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CA",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    atsType: "manual",
    atsSlug: "",
    category: "fintech",
    careersUrl: "https://www.coinbase.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "CB",
  },
  {
    id: "block",
    name: "Block",
    atsType: "greenhouse",
    atsSlug: "block",
    category: "fintech",
    careersUrl: "https://block.xyz/careers/jobs",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "BL",
  },
  {
    id: "affirm",
    name: "Affirm",
    atsType: "greenhouse",
    atsSlug: "affirm",
    category: "fintech",
    careersUrl: "https://www.affirm.com/careers",
    color: MBA_CATEGORY_COLORS.fintech,
    logoInitials: "AF",
  },
  // ── Startup / Growth (public feeds + manual fallbacks) ────────────────────
  {
    id: "airbnb",
    name: "Airbnb",
    atsType: "greenhouse",
    atsSlug: "airbnb",
    category: "startup",
    careersUrl: "https://careers.airbnb.com",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AB",
  },
  {
    id: "lyft",
    name: "Lyft",
    atsType: "greenhouse",
    atsSlug: "lyft",
    category: "startup",
    careersUrl: "https://www.lyft.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "LY",
  },
  {
    id: "doordash",
    name: "DoorDash",
    atsType: "manual",
    atsSlug: "",
    category: "startup",
    careersUrl: "https://careersatdoordash.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DD",
  },
  {
    id: "figma",
    name: "Figma",
    atsType: "greenhouse",
    atsSlug: "figma",
    category: "startup",
    careersUrl: "https://www.figma.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "FG",
  },
  {
    id: "notion",
    name: "Notion",
    atsType: "ashby",
    atsSlug: "notion",
    category: "startup",
    careersUrl: "https://www.notion.so/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "NO",
  },
  {
    id: "airtable",
    name: "Airtable",
    atsType: "greenhouse",
    atsSlug: "airtable",
    category: "startup",
    careersUrl: "https://airtable.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AT",
  },
  {
    id: "rippling",
    name: "Rippling",
    atsType: "manual",
    atsSlug: "",
    category: "startup",
    careersUrl: "https://www.rippling.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "RI",
  },
  {
    id: "asana",
    name: "Asana",
    atsType: "greenhouse",
    atsSlug: "asana",
    category: "startup",
    careersUrl: "https://asana.com/jobs",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "AS",
  },
  {
    id: "reddit",
    name: "Reddit",
    atsType: "greenhouse",
    atsSlug: "reddit",
    category: "startup",
    careersUrl: "https://www.redditinc.com/careers",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "RD",
  },
  {
    id: "datadog",
    name: "Datadog",
    atsType: "greenhouse",
    atsSlug: "datadog",
    category: "startup",
    careersUrl: "https://careers.datadoghq.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DD",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    atsType: "greenhouse",
    atsSlug: "dropbox",
    category: "startup",
    careersUrl: "https://jobs.dropbox.com/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "DB",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    atsType: "greenhouse",
    atsSlug: "hubspot",
    category: "startup",
    careersUrl: "https://www.hubspot.com/careers/jobs",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "HS",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    atsType: "greenhouse",
    atsSlug: "cloudflare",
    category: "startup",
    careersUrl: "https://www.cloudflare.com/careers/jobs/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "CF",
  },
  {
    id: "openai",
    name: "OpenAI",
    atsType: "ashby",
    atsSlug: "openai",
    category: "startup",
    careersUrl: "https://openai.com/careers/search/",
    color: MBA_CATEGORY_COLORS.startup,
    logoInitials: "OA",
  },
  // ── Big Tech (mixed public feeds + manual portals) ────────────────────────
  {
    id: "google",
    name: "Google",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl:
      "https://careers.google.com/jobs/results/?category=BUSINESS_STRATEGY&employment_type=INTERN",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "GO",
  },
  {
    id: "amazon",
    name: "Amazon",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://www.amazon.jobs/content/en/team-category/mba-opportunities",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AM",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://careers.microsoft.com/v2/global/en/students",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "MS",
  },
  {
    id: "meta",
    name: "Meta",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://www.metacareers.com/jobs?roles[0]=intern&q=mba",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "ME",
  },
  {
    id: "apple",
    name: "Apple",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://jobs.apple.com/en-us/search?team=internships-STDNT-INTRN",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AP",
  },
  {
    id: "uber",
    name: "Uber",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://www.uber.com/us/en/careers/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "UB",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    atsType: "lever",
    atsSlug: "atlassian",
    category: "big-tech",
    careersUrl: "https://www.atlassian.com/company/careers/all-jobs",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AT",
  },
  {
    id: "adobe",
    name: "Adobe",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://careers.adobe.com/us/en",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "AD",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://careers.salesforce.com/en/jobs/",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "SF",
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    color: MBA_CATEGORY_COLORS["big-tech"],
    logoInitials: "NV",
  },
];

export const MBA_COMPANY_MAP = new Map<string, MBACompany>(
  MBA_COMPANIES.map((c) => [c.id, c])
);

export const MBA_KEYWORDS = [
  "mba",
  "intern",
  "internship",
  "summer associate",
  "associate product manager",
  "apm",
  "product management intern",
  "strategy intern",
  "operations intern",
  "business development intern",
] as const;
