// ---------------------------------------------------------------------------
// MBA Internship Notifications – company registry
// ---------------------------------------------------------------------------

import type { MBACompany } from "@/types/mba-jobs";

export const MBA_COMPANIES: MBACompany[] = [
  // ── Fintech (Greenhouse) ──────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    atsType: "greenhouse",
    atsSlug: "stripe",
    category: "fintech",
    careersUrl: "https://stripe.com/jobs",
    color: "#635BFF",
    logoInitials: "ST",
  },
  {
    id: "brex",
    name: "Brex",
    atsType: "greenhouse",
    atsSlug: "brex",
    category: "fintech",
    careersUrl: "https://www.brex.com/careers",
    color: "#F0645D",
    logoInitials: "BR",
  },
  {
    id: "plaid",
    name: "Plaid",
    atsType: "greenhouse",
    atsSlug: "plaid",
    category: "fintech",
    careersUrl: "https://plaid.com/careers",
    color: "#2E7CF6",
    logoInitials: "PL",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    atsType: "greenhouse",
    atsSlug: "robinhood",
    category: "fintech",
    careersUrl: "https://careers.robinhood.com",
    color: "#00C805",
    logoInitials: "RH",
  },
  {
    id: "carta",
    name: "Carta",
    atsType: "greenhouse",
    atsSlug: "carta",
    category: "fintech",
    careersUrl: "https://carta.com/careers",
    color: "#00A99D",
    logoInitials: "CA",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    atsType: "lever",
    atsSlug: "coinbase",
    category: "fintech",
    careersUrl: "https://www.coinbase.com/careers",
    color: "#0052FF",
    logoInitials: "CB",
  },
  // ── Startup / Growth (Greenhouse / Lever) ─────────────────────────────────
  {
    id: "airbnb",
    name: "Airbnb",
    atsType: "greenhouse",
    atsSlug: "airbnb",
    category: "startup",
    careersUrl: "https://careers.airbnb.com",
    color: "#FF5A5F",
    logoInitials: "AB",
  },
  {
    id: "lyft",
    name: "Lyft",
    atsType: "greenhouse",
    atsSlug: "lyft",
    category: "startup",
    careersUrl: "https://www.lyft.com/careers",
    color: "#FF00BF",
    logoInitials: "LY",
  },
  {
    id: "doordash",
    name: "DoorDash",
    atsType: "greenhouse",
    atsSlug: "doordash",
    category: "startup",
    careersUrl: "https://careers.doordash.com",
    color: "#FF3008",
    logoInitials: "DD",
  },
  {
    id: "figma",
    name: "Figma",
    atsType: "greenhouse",
    atsSlug: "figma",
    category: "startup",
    careersUrl: "https://www.figma.com/careers",
    color: "#1ABCFE",
    logoInitials: "FG",
  },
  {
    id: "notion",
    name: "Notion",
    atsType: "greenhouse",
    atsSlug: "notion",
    category: "startup",
    careersUrl: "https://www.notion.so/careers",
    color: "#37352F",
    logoInitials: "NO",
  },
  {
    id: "airtable",
    name: "Airtable",
    atsType: "greenhouse",
    atsSlug: "airtable",
    category: "startup",
    careersUrl: "https://airtable.com/careers",
    color: "#FCB400",
    logoInitials: "AT",
  },
  {
    id: "rippling",
    name: "Rippling",
    atsType: "greenhouse",
    atsSlug: "rippling",
    category: "startup",
    careersUrl: "https://www.rippling.com/careers",
    color: "#FF6B35",
    logoInitials: "RI",
  },
  {
    id: "asana",
    name: "Asana",
    atsType: "greenhouse",
    atsSlug: "asana",
    category: "startup",
    careersUrl: "https://asana.com/jobs",
    color: "#F06A6A",
    logoInitials: "AS",
  },
  {
    id: "reddit",
    name: "Reddit",
    atsType: "lever",
    atsSlug: "reddit",
    category: "startup",
    careersUrl: "https://www.redditinc.com/careers",
    color: "#FF4500",
    logoInitials: "RD",
  },
  // ── Big Tech (manual – curated links, no public ATS API) ──────────────────
  {
    id: "google",
    name: "Google",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl:
      "https://careers.google.com/jobs/results/?category=BUSINESS_STRATEGY&employment_type=INTERN",
    color: "#4285F4",
    logoInitials: "GO",
  },
  {
    id: "amazon",
    name: "Amazon",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://www.amazon.jobs/content/en/team-category/mba-opportunities",
    color: "#FF9900",
    logoInitials: "AM",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl:
      "https://jobs.careers.microsoft.com/global/en/search?q=mba+intern&l=en_US&pg=1&pgSz=20",
    color: "#00A4EF",
    logoInitials: "MS",
  },
  {
    id: "meta",
    name: "Meta",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://www.metacareers.com/jobs?roles[0]=intern&q=mba",
    color: "#0866FF",
    logoInitials: "ME",
  },
  {
    id: "apple",
    name: "Apple",
    atsType: "manual",
    atsSlug: "",
    category: "big-tech",
    careersUrl: "https://jobs.apple.com/en-us/search?team=internships-STDNT-INTRN",
    color: "#555555",
    logoInitials: "AP",
  },
  {
    id: "uber",
    name: "Uber",
    atsType: "greenhouse",
    atsSlug: "uber",
    category: "big-tech",
    careersUrl: "https://www.uber.com/us/en/careers",
    color: "#000000",
    logoInitials: "UB",
  },
];

export const MBA_COMPANY_MAP = new Map<string, MBACompany>(
  MBA_COMPANIES.map((c) => [c.id, c])
);

export const MBA_KEYWORDS = [
  "mba",
  "intern",
  "internship",
  "summer associate",
  "associate product manager",
  "apm",
  "product management intern",
  "strategy intern",
  "operations intern",
  "business development intern",
] as const;
