import type { MBAJobRoleFamily } from "@/types/mba-jobs";

export const MBA_ROLE_FAMILIES = [
  "product",
  "product-marketing",
  "strategy",
  "operations",
  "growth",
  "finance",
  "business-development",
  "analytics",
  "chief-of-staff",
] as const satisfies readonly MBAJobRoleFamily[];

export const MBA_ROLE_FAMILY_LABELS: Record<MBAJobRoleFamily | "all", string> = {
  all: "All roles",
  product: "Product",
  "product-marketing": "Product Marketing",
  strategy: "Strategy",
  operations: "Operations",
  growth: "Growth",
  finance: "Finance",
  "business-development": "Business Development",
  analytics: "Analytics",
  "chief-of-staff": "Chief of Staff",
};

export const MBA_ROLE_FAMILY_SEARCH_TERMS: Record<MBAJobRoleFamily, string[]> = {
  product: [
    "product",
    "product manager",
    "product management",
    "product owner",
    "product lead",
    "pm",
    "apm",
    "associate product manager",
  ],
  "product-marketing": [
    "product marketing",
    "product marketing manager",
    "pmm",
    "go to market",
    "gtm",
  ],
  strategy: [
    "strategy",
    "strategic planning",
    "strategic initiatives",
    "corporate strategy",
    "business strategy",
  ],
  operations: [
    "operations",
    "business operations",
    "business ops",
    "bizops",
    "revenue operations",
    "revenue ops",
    "sales operations",
    "sales ops",
    "program operations",
    "program ops",
    "program manager",
    "program management",
  ],
  growth: [
    "growth",
    "growth marketing",
    "lifecycle",
    "acquisition",
    "retention",
    "monetization",
    "demand generation",
  ],
  finance: [
    "finance",
    "strategic finance",
    "corporate finance",
    "fp&a",
    "fp and a",
    "financial planning",
    "treasury",
  ],
  "business-development": [
    "business development",
    "partnerships",
    "partner manager",
    "partnership manager",
    "corporate development",
    "corp dev",
    "commercial strategy",
    "gtm",
    "go to market",
  ],
  analytics: [
    "analytics",
    "business analyst",
    "strategy and analytics",
    "operations analytics",
    "business intelligence",
    "data analyst",
  ],
  "chief-of-staff": [
    "chief of staff",
    "office of the ceo",
    "ceo office",
    "founder associate",
  ],
};
