export const careerTimeline = [
  {
    year: 2018,
    role: "Bachelor of Arts Graduate",
    company: "Florida State University",
    logo: "/images/logos/fsu-logo.png",
    description: "Graduated with degrees in Political Science and International Affairs. The research and policy analysis work gave me the analytical habits I still rely on in product work.",
    techStack: ["Research", "Policy Analysis", "International Relations"],
  },
  {
    year: 2019,
    role: "Digital and Communications Intern",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "Started building data-driven acquisition strategies for digital campaigns. This was where I first saw how analytics could change the way a team makes decisions.",
    techStack: ["Email Marketing", "A/B Testing", "User Acquisition", "Analytics"],
  },
  {
    year: 2020,
    role: "Digital and Data Associate",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "Moved client analytics from manual reporting to automated ETL pipelines with interactive dashboards. Cut decision-making time by 40% and improved conversion 25% through better segmentation.",
    techStack: ["SQL", "Sisense", "Tableau", "ETL Pipelines", "Data Analytics"],
  },
  {
    year: 2021,
    role: "Client Services Manager",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "Ran delivery for 80+ digital programs, coordinating cross-functional teams and keeping campaigns on schedule. 100% on-time delivery and 25% higher engagement through data-driven messaging.",
    techStack: ["Project Management", "Data Analytics", "Stakeholder Management", "Campaign Strategy"],
  },
  {
    year: 2022,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "Moved into QA at a civic tech company, where I got to own product reliability for platforms reaching millions of users. Maintained 99.999% uptime and improved release efficiency by 30%.",
    techStack: ["Manual Testing", "Automated Testing", "Jira", "Quality Strategy"],
  },
  {
    year: 2023,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "Led a cross-functional pricing strategy initiative that brought engineering, sales, and finance together around product value. Generated $4M in additional revenue through market analysis and financial modeling.",
    techStack: ["Product Strategy", "Financial Modeling", "Market Analysis", "Cross-functional Leadership"],
  },
  {
    year: 2024,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "Owned the product vision for the TextOut platform, from user research through requirements and feature prioritization. Drove a 35% engagement increase and cut onboarding time 90% through GCP automation.",
    techStack: ["User Research", "Product Vision", "GCP", "Feature Prioritization", "Analytics"],
  },
  {
    year: 2025,
    role: "Quality Assurance Engineer",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "Led the launch of the RunningMate platform, translating cross-functional feedback into user stories and quality acceptance criteria. Cut critical defects 90%, moved NPS from 23 to 36, and accelerated releases from monthly to biweekly.",
    techStack: ["Product Development", "DevOps Integration", "AI/LLM Tools", "Release Management"],
  },
  {
    year: 2025,
    role: "MBA Candidate",
    company: "UC Berkeley Haas",
    logo: "/images/logos/berkeley-logo.png",
    description: "I'm at Haas to sharpen the strategy side of product work while I continue building things I find interesting. Consortium Fellow and MLT Professional Development Fellow.",
    techStack: ["Product Management", "Strategy", "Venture Capital", "Leadership", "Fintech"],
  },
];
