export const careerTimeline = [
  {
    year: 2018,
    role: "Bachelor of Arts Graduate",
    company: "Florida State University",
    logo: "/images/logos/fsu-logo.png",
    description: "I graduated with degrees in Political Science and International Affairs, and the research and policy analysis work gave me the analytical habits I still rely on in product work.",
    techStack: ["Research", "Policy Analysis", "International Relations"],
  },
  {
    year: 2019,
    role: "Digital and Communications Intern",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "I started building data-driven acquisition strategies for digital campaigns, and this was where I first saw how analytics could change the way a team makes decisions.",
    techStack: ["Email Marketing", "A/B Testing", "User Acquisition", "Analytics"],
  },
  {
    year: 2020,
    role: "Digital and Data Associate",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "I moved client analytics from manual reporting to automated ETL pipelines with interactive dashboards, which cut analysis time 40% and improved conversion 25% through better segmentation.",
    techStack: ["SQL", "Sisense", "Tableau", "ETL Pipelines", "Data Analytics"],
  },
  {
    year: 2021,
    role: "Client Services Manager",
    company: "Open Progress",
    logo: "/images/logos/open-progress-logo.png",
    description: "I ran delivery for more than 80 client campaigns and kept every one on schedule, and the messaging validation frameworks I built lifted response rates 20%.",
    techStack: ["Project Management", "Data Analytics", "Stakeholder Management", "Campaign Strategy"],
  },
  {
    year: 2022,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "I moved into QA at a civic tech company, where I owned product reliability for platforms reaching millions of users. I held uptime at 99.999%, cut critical defects 90%, and improved release efficiency 50%.",
    techStack: ["Manual Testing", "Automated Testing", "Jira", "Quality Strategy"],
  },
  {
    year: 2023,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "I led a cross-functional pricing strategy that brought engineering, sales, and finance together around product value, and it generated $4M in additional revenue through market analysis and financial modeling.",
    techStack: ["Product Strategy", "Financial Modeling", "Market Analysis", "Cross-functional Leadership"],
  },
  {
    year: 2024,
    role: "Quality Assurance Analyst",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "I owned the product vision for the TextOut platform, from user research through requirements and feature prioritization, and that work drove a 35% increase in engagement.",
    techStack: ["User Research", "Product Vision", "Feature Prioritization", "Analytics"],
  },
  {
    year: 2025,
    role: "Quality Assurance Engineer",
    company: "CIVITECH",
    logo: "/images/logos/civitech-logo.png",
    description: "I led the launch of the RunningMate platform, turning cross-functional feedback into user stories and quality acceptance criteria. NPS moved from 23 to 36, releases went from monthly to biweekly, and a Google Cloud event system I built cut client onboarding time 60%.",
    techStack: ["Product Development", "DevOps Integration", "GCP", "AI/LLM Tools", "Release Management"],
  },
  {
    year: 2025,
    role: "MBA Candidate",
    company: "UC Berkeley Haas",
    logo: "/images/logos/berkeley-logo.png",
    description: "I'm at Haas to sharpen the strategy side of product work while I continue building things I find interesting. Consortium Fellow and MLT Professional Development Fellow.",
    techStack: ["Product Management", "Strategy", "Venture Capital", "Leadership", "Fintech"],
  },
  {
    year: 2026,
    role: "Innovation Consultant Team Lead",
    company: "Haas@Work",
    logo: "/images/logos/berkeley-logo.png",
    description: "I lead a client engagement for a global mobility technology company, managing stakeholder communication, workflow execution, and alignment across a consulting team.",
    techStack: ["Consulting", "Stakeholder Management", "Program Execution"],
  },
  {
    year: 2026,
    role: "MBA Growth Intern",
    company: "Juno",
    description: "I spent the summer on Juno's MBA growth team, where I rebuilt the team's reporting into an hourly dashboard, set up conversion measurement, audited the email program, and took over the SMS program as its product manager.",
    techStack: ["Growth Analytics", "SQL", "Google Analytics 4", "Customer.io", "Experimentation"],
  },
];
