export type EarthquakeView = "recent" | "significant" | "regions";

export interface EarthquakeRouteState {
  view: EarthquakeView;
  quake: string | null;
}

/** Descriptive magnitude class, ordered from weakest to strongest. */
export type QuakeTier =
  | "minor"
  | "light"
  | "moderate"
  | "strong"
  | "major"
  | "great";

/** USGS PAGER impact alert level, when one has been issued. */
export type QuakeAlert = "green" | "yellow" | "orange" | "red";

export interface QuakeEvent {
  /** USGS event id, e.g. "us7000n7yz". Used as the deep-link `quake` param. */
  id: string;
  magnitude: number;
  magType: string;
  /** Cleaned USGS place string, e.g. "10 km NE of Ridgecrest, CA". */
  place: string;
  /** Region tail derived from `place` for grouping (state, country, or sea). */
  region: string;
  /** ISO 8601 origin time. */
  time: string;
  depthKm: number;
  longitude: number;
  latitude: number;
  tsunami: boolean;
  /** Number of "Did You Feel It?" reports, when available. */
  felt: number | null;
  alert: QuakeAlert | null;
  /** USGS significance score (0–1000+); higher means more newsworthy. */
  significance: number;
  /** USGS event page URL. */
  url: string;
  tier: QuakeTier;
}

export interface MagnitudeBucket {
  tier: QuakeTier;
  label: string;
  /** Human-readable magnitude band, e.g. "5.0–5.9". */
  range: string;
  count: number;
}

export interface RegionCount {
  region: string;
  count: number;
  maxMagnitude: number;
  /** Event id of the strongest quake in the region, for quick drilldown. */
  strongestId: string | null;
}

export interface EarthquakeHeroStats {
  total24h: number;
  total7d: number;
  /** Events in the past 24h with at least one felt report. */
  felt24h: number;
  strongest24hMag: number | null;
  strongest24hPlace: string | null;
  significant30d: number;
  largest7dMag: number | null;
  tsunamiAlerts7d: number;
  deepestKm: number | null;
}

export interface EarthquakeSummary {
  /** When this snapshot was generated by the build script. */
  generatedAt: string;
  /** USGS feed `metadata.generated` timestamp (ISO), when available. */
  feedUpdated: string | null;
  heroStats: EarthquakeHeroStats;
  /** Most recent notable quakes (past 24h), newest first. */
  recent: QuakeEvent[];
  /** Significant quakes over the past 30 days, strongest first. */
  significant: QuakeEvent[];
  /** Magnitude distribution across the past 7 days. */
  magnitudeBuckets: MagnitudeBucket[];
  /** Busiest regions over the past 7 days, by count. */
  regions: RegionCount[];
  /** Every surfaced quake keyed by id, for the detail panel. */
  quakeDetails: Record<string, QuakeEvent>;
}

export interface EarthquakeSnapshot {
  summary: EarthquakeSummary;
}
