// Route → build-note write-up for the project build-note aside. The purpose/method prose for these routes
// lives in projectBuildNoteContent, loaded through the dynamic
// ProjectBuildNote below so it stays out of the shared first-load bundle.
export const projectBuildNoteLinks: Record<string, string> = {
  "/ai-dev-tools": "/writing/mapping-the-ai-dev-tool-ecosystem",
  "/bay-area-transit": "/writing/building-a-bart-transit-dashboard",
  "/decision-lab": "/writing/building-decision-lab",
  "/earthquake-pulse": "/writing/building-an-earthquake-dashboard",
  "/fantasy-formula-1": "/writing/building-a-fantasy-formula-1-optimizer",
  "/fantasy-football": "/writing/building-a-fantasy-football-rankings-platform",
  "/fintech-tools/budget-planner": "/writing/building-a-budget-planner",
  "/fintech-tools/interchange-iq": "/writing/interchange-iq-payment-fee-analyzer",
  "/food-map": "/writing/building-an-austin-food-map",
  "/formula-1": "/writing/building-a-formula-1-dashboard",
  "/frontier-models": "/writing/building-a-frontier-model-tracker",
  "/golf": "/writing/building-a-pga-tour-dashboard",
  "/github-trending-pulse": "/writing/building-a-github-trending-dashboard",
  "/investments": "/writing/building-an-investment-research-platform",
  "/la-liga": "/writing/building-a-la-liga-dashboard",
  "/mba-internship-notifications": "/writing/building-an-mba-recruiting-tracker",
  "/mlb": "/writing/building-an-mlb-dashboard",
  "/museum-log": "/writing/building-a-museum-log",
  "/nba": "/writing/building-an-nba-dashboard",
  "/news-pulse": "/writing/building-news-pulse-dashboard",
  "/nfl": "/writing/building-an-nfl-dashboard",
  "/polling-aggregator": "/writing/building-a-polling-aggregator",
  "/premier-league": "/writing/building-a-premier-league-dashboard",
  "/recipe-finder": "/writing/building-a-pantry-aware-recipe-finder",
  "/spacex-mission-control": "/writing/building-spacex-mission-control",
  "/tech-startup-tracker": "/writing/building-a-tech-startup-tracker",
  "/travel": "/writing/building-a-travel-planner",
  "/wine-cellar": "/writing/building-a-wine-cellar-app",
  "/world-cup-2026": "/writing/building-a-world-cup-dashboard",
};
