#!/usr/bin/env tsx
/**
 * Refreshes src/data/golfSnapshot.ts from ESPN's public golf leaderboard.
 *
 *   npm run update:golf
 *
 * ESPN's site API needs no token. The script tracks whichever PGA Tour event
 * ESPN is currently featuring (in-progress event preferred, else most recent).
 * If the fetch or parse fails, the existing snapshot is kept instead of being
 * wiped — matching the Formula 1 pipeline.
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildGolfSnapshotData } from "../src/lib/golfData";
import type { GolfSnapshot } from "../src/types/golf";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

function hasContents(snapshot: GolfSnapshot | null): snapshot is GolfSnapshot {
  return Boolean(snapshot && snapshot.summary.leaderboard.length > 0);
}

async function main() {
  const outPath = resolve(__dirname, "../src/data/golfSnapshot.ts");

  let snapshot: GolfSnapshot;
  try {
    console.log("⛳ Building golf snapshot from ESPN…");
    snapshot = await buildGolfSnapshotData();
  } catch (error) {
    const existing = readGeneratedSnapshot<GolfSnapshot>(outPath, "golfSnapshot");
    if (hasContents(existing)) {
      console.warn(
        "⛳ Golf snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  const output = `import type { GolfSnapshot } from "@/types/golf";

// Auto-generated by scripts/buildGolfSnapshot.ts on ${
    snapshot.summary.tournament?.generatedAt ?? new Date().toISOString()
  }
export const golfSnapshot: GolfSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(outPath, output);

  const tournament = snapshot.summary.tournament;
  console.log(
    `⛳ Done. ${tournament?.name ?? "Unknown event"} — ` +
      `${snapshot.summary.leaderboard.length} players, leader ` +
      `${snapshot.summary.heroStats.leaderName ?? "?"} ` +
      `(${snapshot.summary.heroStats.leaderScore ?? "?"}).`
  );
}

main().catch((err) => {
  console.error("Golf snapshot update failed:", err);
  process.exit(1);
});
