import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { buildFormula1SnapshotData } from "../src/lib/formula1Data";
import type { Formula1Snapshot } from "../src/types/formula1";

export interface BuildFormula1SnapshotOptions {
  projectRoot?: string;
  logger?: Pick<Console, "log" | "error">;
}

export interface BuildFormula1SnapshotResult {
  snapshotPath: string;
  snapshot: Formula1Snapshot;
}

const SNAPSHOT_PATH_SEGMENTS = ["src", "data", "formula1Snapshot.ts"] as const;

function hasSnapshotContents(snapshot: Formula1Snapshot | null): boolean {
  return Boolean(snapshot && snapshot.meetings.length > 0);
}

async function readExistingSnapshot(snapshotPath: string): Promise<Formula1Snapshot | null> {
  try {
    const rawSnapshot = await fs.readFile(snapshotPath, "utf8");
    const match = rawSnapshot.match(
      /export const formula1Snapshot: Formula1Snapshot = (\{[\s\S]*\});\s*$/
    );

    if (!match) {
      return null;
    }

    return JSON.parse(match[1]) as Formula1Snapshot;
  } catch (error) {
    const err = error as NodeJS.ErrnoException;
    if (err.code === "ENOENT") {
      return null;
    }

    throw error;
  }
}

export async function buildFormula1Snapshot(
  options: BuildFormula1SnapshotOptions = {}
): Promise<BuildFormula1SnapshotResult> {
  const projectRoot = options.projectRoot ?? process.cwd();
  const logger = options.logger ?? console;
  const snapshotPath = path.join(projectRoot, ...SNAPSHOT_PATH_SEGMENTS);
  const existingSnapshot = await readExistingSnapshot(snapshotPath);

  let snapshot: Formula1Snapshot;

  try {
    snapshot = await buildFormula1SnapshotData();
  } catch (error) {
    if (hasSnapshotContents(existingSnapshot)) {
      logger.log("Formula 1 snapshot refresh failed. Keeping the existing snapshot.");
      return {
        snapshotPath,
        snapshot: existingSnapshot as Formula1Snapshot,
      };
    }

    throw error;
  }

  const fileContents = `import type { Formula1Snapshot } from "@/types/formula1";

// Generated by scripts/buildFormula1Snapshot.ts.
export const formula1Snapshot: Formula1Snapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  await fs.mkdir(path.dirname(snapshotPath), { recursive: true });
  // Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so
  // the destination file is never observed in a half-written state if the
  // process is killed mid-write.
  const tmpPath = `${snapshotPath}.tmp`;
  await fs.writeFile(tmpPath, fileContents, "utf8");
  await fs.rename(tmpPath, snapshotPath);

  logger.log(
    `Formula 1 snapshot written: ${snapshot.meetings.length} meetings, ${snapshot.driverStandings.length} drivers, ${snapshot.constructorStandings.length} constructors.`
  );

  return {
    snapshotPath,
    snapshot,
  };
}

async function main() {
  await buildFormula1Snapshot();
}

const isMainModule =
  process.argv[1] !== undefined &&
  // @ts-expect-error - import.meta works at runtime via tsx (not via tsc-emitted CJS)
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMainModule) {
  main().catch((error) => {
    console.error("Failed to build Formula 1 snapshot:", error);
    process.exitCode = 1;
  });
}
