#!/usr/bin/env tsx
/**
 * Refreshes src/data/bayAreaTransitSnapshot.ts from BART's public API.
 *
 *   npm run update:bay-area-transit
 *
 * BART's legacy API needs no token (the published demo key is baked into the
 * builder). If the fetch or parse fails, the existing snapshot stays on disk
 * and the command exits nonzero so automation reports the failed attempt.
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildBayAreaTransitSnapshotData } from "../src/lib/bayAreaTransitData";
import type { TransitSnapshot } from "../src/types/bayAreaTransit";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

function hasContents(
  snapshot: TransitSnapshot | null
): snapshot is TransitSnapshot {
  return Boolean(
    snapshot &&
      snapshot.summary.lines.length > 0 &&
      snapshot.summary.stations.length > 0
  );
}

async function main() {
  const outPath = resolve(
    __dirname,
    "../src/data/bayAreaTransitSnapshot.ts"
  );

  let snapshot: TransitSnapshot;
  try {
    console.log("🚆 Building Bay Area transit snapshot from BART…");
    snapshot = await buildBayAreaTransitSnapshotData();
  } catch (error) {
    const existing = readGeneratedSnapshot<TransitSnapshot>(
      outPath,
      "bayAreaTransitSnapshot"
    );
    if (hasContents(existing)) {
      console.warn(
        "🚆 Transit snapshot refresh failed; keeping the existing snapshot.",
        error
      );
    }
    throw error;
  }

  const output = `import type { TransitSnapshot } from "@/types/bayAreaTransit";

// Auto-generated by scripts/buildBayAreaTransitSnapshot.ts on ${
    snapshot.summary.system?.generatedAt ?? new Date().toISOString()
  }
export const bayAreaTransitSnapshot: TransitSnapshot = ${JSON.stringify(
    snapshot,
    null,
    2
  )};
`;
  writeFileAtomic(outPath, output);

  const { heroStats } = snapshot.summary;
  console.log(
    `🚆 Done. ${heroStats.lineCount} lines, ${heroStats.stationCount} stations, ` +
      `${heroStats.trainsTracked} trains tracked, ` +
      `${heroStats.activeAdvisories} advisories, ` +
      `${heroStats.elevatorOutages} elevator outages.`
  );
}

main().catch((err) => {
  console.error("Bay Area transit snapshot update failed:", err);
  process.exit(1);
});
