#!/usr/bin/env tsx
// Refreshes the score-pools snapshot: fixtures, results, and standings from
// API-Football, odds from The Odds API, merged with manual entries
// (scripts/data/scorePools.manual.ts) and CSV drops
// (scripts/data/score-pools/*.csv, filename = league key). Odds history is
// append-only and capped per fixture so line movement stays queryable.
//
// Runs without keys too — provider leagues then carry a note and only
// manual/CSV data. A failed refresh keeps the previous snapshot.

import { readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildScorePoolsSnapshotData } from "../src/lib/scorePoolsData";
import {
  parseScorePoolsCsv,
  type ManualFixtureInput,
} from "../src/lib/scorePools/providers/manual";
import type { ScorePoolsSnapshot } from "../src/types/scorePools";
import { readGeneratedSnapshot } from "./snapshotFallback";
import { MANUAL_SCORE_POOL_LEAGUES } from "./data/scorePools.manual";
import { SCORE_POOL_LEAGUES } from "./data/scorePoolsConfig";

function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

function hasContents(snapshot: ScorePoolsSnapshot | null): snapshot is ScorePoolsSnapshot {
  return Boolean(snapshot && snapshot.leagues.length > 0);
}

function readCsvFixtures(): Record<string, ManualFixtureInput[]> {
  const dir = resolve(__dirname, "data/score-pools");
  let files: string[] = [];
  try {
    files = readdirSync(dir).filter((file) => file.endsWith(".csv"));
  } catch {
    return {};
  }
  const byLeague: Record<string, ManualFixtureInput[]> = {};
  for (const file of files) {
    const leagueKey = file.replace(/\.csv$/, "");
    const text = readFileSync(resolve(dir, file), "utf8");
    byLeague[leagueKey] = [...(byLeague[leagueKey] ?? []), ...parseScorePoolsCsv(text)];
  }
  return byLeague;
}

async function main() {
  const outPath = resolve(__dirname, "../src/data/scorePoolsSnapshot.ts");
  const previous = readGeneratedSnapshot<ScorePoolsSnapshot>(outPath, "scorePoolsSnapshot");

  let snapshot: ScorePoolsSnapshot;
  try {
    snapshot = await buildScorePoolsSnapshotData({
      leagues: SCORE_POOL_LEAGUES,
      manualLeagues: MANUAL_SCORE_POOL_LEAGUES,
      csvFixturesByLeague: readCsvFixtures(),
      previous,
      keys: {
        theOddsApi: process.env.THE_ODDS_API_KEY ?? null,
        apiFootball: process.env.API_FOOTBALL_KEY ?? null,
      },
    });
  } catch (error) {
    if (hasContents(previous)) {
      console.warn("⚽ Score-pools refresh failed; keeping the existing snapshot.", error);
      return;
    }
    throw error;
  }

  const output = `import type { ScorePoolsSnapshot } from "@/types/scorePools";

// Auto-generated by scripts/buildScorePoolsSnapshot.ts on ${snapshot.generatedAt}
export const scorePoolsSnapshot: ScorePoolsSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(outPath, output);

  const fixtureCount = snapshot.leagues.reduce((sum, league) => sum + league.fixtures.length, 0);
  const oddsCount = snapshot.leagues.reduce(
    (sum, league) =>
      sum + league.fixtures.reduce((inner, fixture) => inner + fixture.odds.length, 0),
    0,
  );
  console.log(
    `⚽ Score-pools snapshot written: ${snapshot.leagues.length} league(s), ${fixtureCount} fixture(s), ${oddsCount} odds snapshot(s).`,
  );
  for (const league of snapshot.leagues) {
    for (const note of league.notes) {
      console.log(`   [${league.key}] ${note}`);
    }
  }
}

main().catch((error) => {
  console.error("Score-pools snapshot build failed:", error);
  process.exit(1);
});
