#!/usr/bin/env tsx
/**
 * Refreshes src/data/earthquakeSnapshot.ts from the USGS Earthquake Hazards
 * Program public GeoJSON feeds.
 *
 *   npm run update:earthquake
 *
 * The USGS feeds need no token. If the fetch or parse fails, the existing
 * snapshot is kept instead of being wiped — matching the Formula 1 / golf
 * pipelines.
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildEarthquakeSnapshotData } from "../src/lib/earthquakeData";
import type { EarthquakeSnapshot } from "../src/types/earthquake";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

function hasContents(
  snapshot: EarthquakeSnapshot | null
): snapshot is EarthquakeSnapshot {
  return Boolean(
    snapshot &&
      (snapshot.summary.recent.length > 0 ||
        snapshot.summary.significant.length > 0)
  );
}

async function main() {
  const outPath = resolve(__dirname, "../src/data/earthquakeSnapshot.ts");

  let snapshot: EarthquakeSnapshot;
  try {
    console.log("🌎 Building earthquake snapshot from USGS feeds…");
    snapshot = await buildEarthquakeSnapshotData();
  } catch (error) {
    const existing = readGeneratedSnapshot<EarthquakeSnapshot>(
      outPath,
      "earthquakeSnapshot"
    );
    if (hasContents(existing)) {
      console.warn(
        "🌎 Earthquake snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  const output = `import type { EarthquakeSnapshot } from "@/types/earthquake";

// Auto-generated by scripts/buildEarthquakeSnapshot.ts on ${snapshot.summary.generatedAt}
export const earthquakeSnapshot: EarthquakeSnapshot = ${JSON.stringify(
    snapshot,
    null,
    2
  )};
`;
  writeFileAtomic(outPath, output);

  const stats = snapshot.summary.heroStats;
  console.log(
    `🌎 Done. ${stats.total24h} quakes in 24h, ${stats.total7d} over 7 days, ` +
      `${snapshot.summary.significant.length} significant. Strongest 24h: ` +
      `M${stats.strongest24hMag ?? "?"} (${stats.strongest24hPlace ?? "?"}).`
  );
}

main().catch((err) => {
  console.error("Earthquake snapshot update failed:", err);
  process.exit(1);
});
