#!/usr/bin/env tsx
/**
 * Refreshes src/data/worldCupSnapshot.ts from ESPN's public soccer/fifa.world
 * endpoints.
 *
 *   npm run update:world-cup
 *
 * ESPN's site API needs no token. If the fetch or parse fails (or the feed has
 * not populated yet, which is normal before kickoff), the existing snapshot is
 * kept instead of being wiped — matching the Formula 1 and golf pipelines. The
 * stable tournament facts (hosts, venues, format, dates) always survive a
 * refresh because the builder carries them forward from the current file.
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildWorldCupSnapshotData } from "../src/lib/worldCupData";
import type { WorldCupSnapshot } from "../src/types/worldCup";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

function hasValidTournament(
  snapshot: WorldCupSnapshot | null
): snapshot is WorldCupSnapshot {
  return Boolean(snapshot && snapshot.tournament && snapshot.tournament.name);
}

async function main() {
  const outPath = resolve(__dirname, "../src/data/worldCupSnapshot.ts");

  let snapshot: WorldCupSnapshot;
  try {
    console.log("🏆 Building World Cup snapshot from ESPN…");
    snapshot = await buildWorldCupSnapshotData();
  } catch (error) {
    const existing = readGeneratedSnapshot<WorldCupSnapshot>(
      outPath,
      "worldCupSnapshot"
    );
    if (hasValidTournament(existing)) {
      console.warn(
        "🏆 World Cup snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  const output = `import type { WorldCupSnapshot } from "@/types/worldCup";

// Auto-generated by scripts/buildWorldCupSnapshot.ts on ${snapshot.tournament.generatedAt}
export const worldCupSnapshot: WorldCupSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(outPath, output);

  console.log(
    `🏆 Done. ${snapshot.tournament.name} — ${snapshot.teamOptions.length} teams, ` +
      `${snapshot.groups.length} groups, ${snapshot.recentFixtures.length} results, ` +
      `${snapshot.upcomingFixtures.length} upcoming. Phase: ${snapshot.tournament.phase}.`
  );
}

main().catch((err) => {
  console.error("World Cup snapshot update failed:", err);
  process.exit(1);
});
