import { config } from "dotenv";
import { promises as fs } from "fs";
import path from "path";
config({ path: path.resolve(__dirname, "../.env.local") });
import { buildPremierLeagueSnapshot } from "../src/lib/premierLeagueData";

const PROJECT_ROOT = process.cwd();
const OUTPUT_FILE = path.join(PROJECT_ROOT, "src", "data", "premierLeagueSnapshot.ts");

async function main() {
  const snapshot = await buildPremierLeagueSnapshot();
  const fileContents = `import type { PremierLeagueSnapshot } from "@/types/premier-league";

// Generated by scripts/buildPremierLeagueSnapshot.ts.
export const premierLeagueSnapshot: PremierLeagueSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  await fs.writeFile(OUTPUT_FILE, fileContents, "utf8");
}

main().catch((error) => {
  console.error("Failed to build Premier League snapshot:", error);
  process.exitCode = 1;
});
