import { config } from "dotenv";
import { promises as fs } from "fs";
import path from "path";
config({ path: path.resolve(__dirname, "../.env.local") });
import { buildPremierLeagueSnapshot } from "../src/lib/premierLeagueData";
import type { PremierLeagueSnapshot } from "../src/types/premier-league";
import { readGeneratedSnapshot } from "./snapshotFallback";

const PROJECT_ROOT = process.cwd();
const OUTPUT_FILE = path.join(PROJECT_ROOT, "src", "data", "premierLeagueSnapshot.ts");

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
async function writeFileAtomic(filePath: string, content: string): Promise<void> {
  const tmp = `${filePath}.tmp`;
  await fs.writeFile(tmp, content, "utf8");
  await fs.rename(tmp, filePath);
}

function hasStandings(snapshot: PremierLeagueSnapshot | null): boolean {
  return Boolean(snapshot && snapshot.summary.standings.length > 0);
}

async function main() {
  console.log("Fetching Premier League snapshot from football-data.org…");

  let snapshot: PremierLeagueSnapshot;
  try {
    snapshot = await buildPremierLeagueSnapshot();
  } catch (error) {
    // A failed refresh (network/auth/rate-limit) must not wipe the committed
    // snapshot. Fall back to the last good data instead of overwriting it.
    const existing = readGeneratedSnapshot<PremierLeagueSnapshot>(
      OUTPUT_FILE,
      "premierLeagueSnapshot"
    );
    if (hasStandings(existing)) {
      console.warn(
        "Premier League snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  // A successful build with no standings (schema drift / a thin upstream
  // response) must not overwrite the good committed snapshot either. This
  // mirrors the La Liga refresher's guard.
  if (!hasStandings(snapshot)) {
    const existing = readGeneratedSnapshot<PremierLeagueSnapshot>(
      OUTPUT_FILE,
      "premierLeagueSnapshot"
    );
    if (hasStandings(existing)) {
      console.warn(
        "Premier League snapshot build returned no standings; keeping the existing snapshot."
      );
      return;
    }
  }

  const fileContents = `import type { PremierLeagueSnapshot } from "@/types/premier-league";

// Generated by scripts/buildPremierLeagueSnapshot.ts.
export const premierLeagueSnapshot: PremierLeagueSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  await writeFileAtomic(OUTPUT_FILE, fileContents);
  console.log(
    `Done. Wrote ${snapshot.summary.standings.length} standings rows, ${snapshot.summary.scorers.length} scorers, ${Object.keys(snapshot.teamSnapshots).length} team snapshots.`
  );
}

main().catch((error) => {
  console.error("Failed to build Premier League snapshot:", error);
  process.exitCode = 1;
});
