#!/usr/bin/env tsx
/**
 * Updates src/data/mlbSnapshot.ts with live data from the MLB Stats API.
 * The MLB Stats API is publicly accessible and does not require an auth token.
 *
 * Usage: npx tsx scripts/updateMlbSnapshot.ts
 *        npx tsx scripts/updateMlbSnapshot.ts --league-only
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildMlbSnapshot } from "../src/lib/mlbData";
import type { MlbSnapshot } from "../src/types/mlb";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

async function main() {
  const skipTeamSnapshots = process.argv.includes("--league-only");
  console.log(
    `Fetching MLB snapshot from MLB Stats API${skipTeamSnapshots ? " (league only)" : ""}…`
  );
  const outPath = resolve(__dirname, "../src/data/mlbSnapshot.ts");

  let snapshot: MlbSnapshot;
  try {
    snapshot = await buildMlbSnapshot({ skipTeamSnapshots });
  } catch (error) {
    const existing = readGeneratedSnapshot<MlbSnapshot>(outPath, "mlbSnapshot");
    if (existing && existing.standings.length > 0) {
      console.warn(
        "MLB snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  // A successful build with empty standings (off-season / schema drift) must not
  // overwrite the good committed snapshot. Fall back to the existing data.
  if (snapshot.standings.length === 0) {
    const existing = readGeneratedSnapshot<MlbSnapshot>(outPath, "mlbSnapshot");
    if (existing && existing.standings.length > 0) {
      console.warn(
        "MLB snapshot build returned no standings; keeping the existing snapshot."
      );
      return;
    }
  }

  const output = `import type { MlbSnapshot } from "@/types/mlb";

// Auto-generated by scripts/updateMlbSnapshot.ts on ${snapshot.updatedAt}
export const mlbSnapshot: MlbSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  writeFileAtomic(outPath, output);
  console.log(
    `Done. Wrote ${snapshot.teams.length} teams, ${snapshot.standings.length} standings rows, ${snapshot.recentGames.length} recent games, ${snapshot.upcomingGames.length} upcoming games, ${Object.keys(snapshot.teamSnapshots).length} team snapshots.`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
