#!/usr/bin/env tsx
/**
 * Refreshes football snapshot data from football-data.org.
 *
 * Used two ways:
 *   npm run build          → prebuild runs this with --league-only
 *                            Fetches standings, fixtures, scorers only (~5 req/league, <2 min total).
 *                            Safe within Netlify's 15-min build timeout.
 *
 *   npm run update:football → runs WITHOUT --league-only
 *                             Also fetches per-team fixtures and form (~65 req/league, ~16 min total).
 *                             Run locally when you want sidebar fixture data refreshed.
 *
 * Skips silently if FOOTBALL_DATA_API_TOKEN is not set.
 */

import { config } from "dotenv";
import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
config({ path: resolve(__dirname, "../.env.local") });

import { buildLaLigaSnapshot } from "../src/lib/laLigaData";
import { buildPremierLeagueSnapshot } from "../src/lib/premierLeagueData";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

const token = process.env.FOOTBALL_DATA_API_TOKEN;
const leagueOnly = process.argv.includes("--league-only");

if (!token) {
  // Use ::warning:: so this surfaces in GitHub Actions / Netlify build logs
  // as a *warning*, not a buried info-level log line. Also write to stderr so
  // it's visible even when stdout is captured/silenced.
  const message =
    "FOOTBALL_DATA_API_TOKEN not set — skipping football snapshot update. " +
    "Football snapshots will not refresh on this build. " +
    "Set the secret in GitHub Actions (or Netlify env vars) to re-enable.";
  console.warn(`::warning::${message}`);
  console.error(`⚠️  ${message}`);
  // Still exit 0 — this is a soft skip so deploys without the secret still
  // succeed (e.g. PR previews on forks). The visible warning is the signal.
  process.exit(0);
}

if (leagueOnly) {
  console.log("⚽ Running in league-only mode (standings + fixtures + scorers, no team snapshots).");
}

async function updateLaLiga() {
  console.log("⚽ Fetching La Liga snapshot…");
  const snapshot = await buildLaLigaSnapshot({ skipTeamSnapshots: leagueOnly });
  const output = `import type { LaLigaSnapshot } from "@/types/la-liga";

// Auto-generated by scripts/updateFootballSnapshots.ts on ${snapshot.updatedAt}
export const laLigaSnapshot: LaLigaSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(resolve(__dirname, "../src/data/laLigaSnapshot.ts"), output);
  console.log(
    `   La Liga: ${snapshot.clubs.length} clubs, ${snapshot.scorers.length} scorers, ${snapshot.recentFixtures.length} recent fixtures, ${Object.keys(snapshot.teamSnapshots).length} team snapshots`
  );
}

async function updatePremierLeague() {
  console.log("⚽ Fetching Premier League snapshot…");
  const snapshot = await buildPremierLeagueSnapshot({ skipTeamSnapshots: leagueOnly });
  const output = `import type { PremierLeagueSnapshot } from "@/types/premier-league";

// Auto-generated by scripts/updateFootballSnapshots.ts on ${snapshot.summary.generatedAt}
export const premierLeagueSnapshot: PremierLeagueSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(resolve(__dirname, "../src/data/premierLeagueSnapshot.ts"), output);
  console.log(
    `   Premier League: ${snapshot.summary.standings.length} clubs, ${snapshot.summary.scorers.length} scorers, ${Object.keys(snapshot.teamSnapshots).length} team snapshots`
  );
}

async function main() {
  await updateLaLiga();
  // Wait between leagues so rate-limit window clears
  console.log("⚽ Waiting 30 s before Premier League fetch…");
  await new Promise((resolve) => setTimeout(resolve, 30_000));
  await updatePremierLeague();
  console.log("⚽ Done.");
}

main().catch((err) => {
  console.error("Football snapshot update failed:", err);
  if (leagueOnly) {
    // Deploy prebuild: a transient football-data.org error must not fail the
    // whole build. Warn and exit 0 so the deploy proceeds with the committed
    // snapshot — atomic writes (writeFileAtomic) mean a partial refresh never
    // corrupts a file — mirroring the "failed fetch keeps the previous
    // snapshot" pattern the other snapshot dashboards use. Manual full runs
    // (npm run update:football, no --league-only) still exit 1 so failures
    // surface locally.
    const message =
      "Football snapshot prebuild failed; continuing the build with the committed snapshot.";
    console.warn(`::warning::${message}`);
    console.error(`⚠️  ${message}`);
    process.exit(0);
  }
  process.exit(1);
});
