#!/usr/bin/env tsx
/**
 * Refreshes src/data/nflSnapshot.ts using NFLverse open data.
 *
 *   npm run update:nfl
 *
 * Pulls standings, schedule + scores, team metadata, and player stat
 * leaders from raw.githubusercontent.com (no API key required). Always
 * targets the most recent NFL season present in the standings CSV.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildNflSnapshot } from "../src/lib/nflData";

async function main() {
  const leagueOnly = process.argv.includes("--league-only");
  if (leagueOnly) {
    console.log(
      "🏈 Running in league-only mode (skip per-team snapshots and player leaders)."
    );
  }

  console.log("🏈 Building NFL snapshot from NFLverse…");
  const snapshot = await buildNflSnapshot({
    skipPlayerLeaders: leagueOnly,
    skipTeamSnapshots: leagueOnly,
  });

  const output = `import type { NFLSnapshot } from "@/types/nfl";

// Auto-generated by scripts/updateNflSnapshot.ts on ${snapshot.updatedAt}
export const nflSnapshot: NFLSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  const outPath = resolve(__dirname, "../src/data/nflSnapshot.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(
    `🏈 Done. Season ${snapshot.season} (week ${snapshot.week}). ` +
      `${snapshot.teams.length} teams, ` +
      `${snapshot.recentFixtures.length} recent fixtures, ` +
      `${snapshot.upcomingFixtures.length} upcoming fixtures, ` +
      `${snapshot.leaders.passing.length} passing leaders, ` +
      `${Object.keys(snapshot.teamSnapshots).length} team snapshots.`
  );
}

main().catch((err) => {
  console.error("NFL snapshot update failed:", err);
  process.exit(1);
});
