#!/usr/bin/env tsx
/**
 * Updates src/data/laLigaSnapshot.ts with live data from football-data.org.
 * Requires FOOTBALL_DATA_API_TOKEN in environment.
 *
 * Usage: npx tsx scripts/updateLaLigaSnapshot.ts
 */

import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
config({ path: resolve(__dirname, "../.env.local") });
import { buildLaLigaSnapshot } from "../src/lib/laLigaData";

async function main() {
  console.log("Fetching La Liga snapshot from football-data.org…");
  const snapshot = await buildLaLigaSnapshot();
  const output = `import type { LaLigaSnapshot } from "@/types/la-liga";

// Auto-generated by scripts/updateLaLigaSnapshot.ts on ${snapshot.updatedAt}
export const laLigaSnapshot: LaLigaSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  const outPath = resolve(__dirname, "../src/data/laLigaSnapshot.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(`Done. Wrote ${snapshot.clubs.length} clubs, ${snapshot.scorers.length} scorers, ${snapshot.recentFixtures.length} recent fixtures, ${Object.keys(snapshot.teamSnapshots).length} team snapshots.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
