#!/usr/bin/env tsx
/**
 * Refreshes src/data/nflSnapshot.ts using NFLverse open data.
 *
 *   npm run update:nfl
 *
 * Pulls standings, schedule + scores, team metadata, and player stat
 * leaders from raw.githubusercontent.com (no API key required). Always
 * targets the most recent NFL season present in the standings CSV.
 */

import { resolve } from "node:path";

import { buildNflSnapshot } from "../src/lib/nflData";
import type { NFLSnapshot } from "../src/types/nfl";
import { buildOrKeepExisting, writeFileAtomic } from "./snapshotFallback";

async function main() {
  const outPath = resolve(__dirname, "../src/data/nflSnapshot.ts");

  console.log("🏈 Building NFL snapshot from NFLverse…");
  const snapshot = await buildOrKeepExisting(
    outPath,
    "nflSnapshot",
    "NFL",
    () => buildNflSnapshot(),
    (built: NFLSnapshot) => built.teams.length > 0
  );
  if (!snapshot) {
    // The kept snapshot can still pass the freshness check, so the exit code
    // is what reports this run.
    process.exitCode = 1;
    return;
  }

  const output = `import type { NFLSnapshot } from "@/types/nfl";

// Auto-generated by scripts/updateNflSnapshot.ts on ${snapshot.updatedAt}
export const nflSnapshot: NFLSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(outPath, output);
  console.log(
    `🏈 Done. Season ${snapshot.season} (week ${snapshot.week}). ` +
      `${snapshot.teams.length} teams, ` +
      `${snapshot.recentFixtures.length} recent fixtures, ` +
      `${snapshot.upcomingFixtures.length} upcoming fixtures, ` +
      `${snapshot.leaders.passing.length} passing leaders, ` +
      `${Object.keys(snapshot.teamSnapshots).length} team snapshots.`
  );
}

main().catch((err) => {
  console.error("NFL snapshot update failed:", err);
  process.exit(1);
});
