#!/usr/bin/env tsx
/**
 * Updates src/data/nbaSnapshot.ts with live data from ESPN's public NBA API.
 * No API key is required.
 *
 * Usage: npm run update:nba (standings, leaders, and per-team schedules, about a minute)
 */

import { config } from "dotenv";
import { resolve } from "node:path";
config({ path: resolve(__dirname, "../.env.local") });
import { buildNbaSnapshot, preservePriorFixtures } from "../src/lib/nbaData";
import type { NbaSnapshot } from "../src/types/nba";
import { buildOrKeepExisting, readGeneratedSnapshot, writeFileAtomic } from "./snapshotFallback";

function hasNbaContents(snapshot: NbaSnapshot | null | undefined): boolean {
  return Boolean(
    snapshot &&
      (snapshot.teamsByConference.east.length > 0 ||
        snapshot.teamsByConference.west.length > 0)
  );
}

async function main() {
  console.log("🏀 Fetching NBA snapshot from ESPN…");
  const outPath = resolve(__dirname, "../src/data/nbaSnapshot.ts");

  let snapshot = await buildOrKeepExisting(
    outPath,
    "nbaSnapshot",
    "NBA",
    () => buildNbaSnapshot(),
    hasNbaContents
  );
  // An ESPN 200 with empty arrays never overwrites the committed file, even
  // when the committed one is empty too.
  if (!snapshot || !hasNbaContents(snapshot)) return;

  // Off-season / transient-blip guard: ESPN's scoreboard window is empty all
  // summer while standings and leaders keep serving the completed season. Carry
  // the committed snapshot's fixtures forward so a standings/leaders/season
  // refresh commits on its own without regressing fixtures to zero.
  const existing = readGeneratedSnapshot<NbaSnapshot>(outPath, "nbaSnapshot");
  const fixturesBefore =
    snapshot.recentFixtures.length + snapshot.upcomingFixtures.length;
  snapshot = preservePriorFixtures(snapshot, existing);
  if (snapshot.recentFixtures.length + snapshot.upcomingFixtures.length > fixturesBefore) {
    console.log(
      "🏀 Scoreboard window was empty; carried prior fixtures forward (off-season/blip)."
    );
  }

  const output = `import type { NbaSnapshot } from "@/types/nba";

// Auto-generated by scripts/updateNbaSnapshot.ts on ${snapshot.updatedAt}
export const nbaSnapshot: NbaSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

  writeFileAtomic(outPath, output);
  const east = snapshot.teamsByConference.east.length;
  const west = snapshot.teamsByConference.west.length;
  console.log(
    `   NBA: East ${east} · West ${west} · ${snapshot.scorers.length} scorers · ${snapshot.recentFixtures.length} recent · ${snapshot.upcomingFixtures.length} upcoming · ${Object.keys(snapshot.teamSnapshots).length} team snapshots`
  );
}

main().catch((err) => {
  console.error("NBA snapshot update failed:", err);
  process.exit(1);
});
