#!/usr/bin/env tsx
/**
 * Refreshes src/data/nflSnapshot.ts using NFLverse open data.
 *
 *   npm run update:nfl
 *
 * Pulls standings, schedule + scores, team metadata, and player stat
 * leaders from raw.githubusercontent.com (no API key required). Always
 * targets the most recent NFL season present in the standings CSV.
 */

import { renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildNflSnapshot } from "../src/lib/nflData";
import type { NFLSnapshot } from "../src/types/nfl";
import { readGeneratedSnapshot } from "./snapshotFallback";

/**
 * Atomic write: write to .tmp then rename. Renames are atomic on POSIX, so the
 * destination file is never observed in a half-written state if the process is
 * killed mid-write.
 */
function writeFileAtomic(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, path);
}

async function main() {
  const leagueOnly = process.argv.includes("--league-only");
  if (leagueOnly) {
    console.log(
      "🏈 Running in league-only mode (skip per-team snapshots and player leaders)."
    );
  }

  const outPath = resolve(__dirname, "../src/data/nflSnapshot.ts");

  console.log("🏈 Building NFL snapshot from NFLverse…");
  let snapshot: NFLSnapshot;
  try {
    snapshot = await buildNflSnapshot({
      skipPlayerLeaders: leagueOnly,
      skipTeamSnapshots: leagueOnly,
    });
  } catch (error) {
    const existing = readGeneratedSnapshot<NFLSnapshot>(outPath, "nflSnapshot");
    if (existing && existing.teams.length > 0) {
      console.warn(
        "🏈 NFL snapshot refresh failed; keeping the existing snapshot.",
        error
      );
      return;
    }
    throw error;
  }

  // A successful build with no teams (off-season / schema drift) must not
  // overwrite the good committed snapshot. Fall back to the existing data.
  if (snapshot.teams.length === 0) {
    const existing = readGeneratedSnapshot<NFLSnapshot>(outPath, "nflSnapshot");
    if (existing && existing.teams.length > 0) {
      console.warn(
        "🏈 NFL snapshot build returned no teams; keeping the existing snapshot."
      );
      return;
    }
  }

  const output = `import type { NFLSnapshot } from "@/types/nfl";

// Auto-generated by scripts/updateNflSnapshot.ts on ${snapshot.updatedAt}
export const nflSnapshot: NFLSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileAtomic(outPath, output);
  console.log(
    `🏈 Done. Season ${snapshot.season} (week ${snapshot.week}). ` +
      `${snapshot.teams.length} teams, ` +
      `${snapshot.recentFixtures.length} recent fixtures, ` +
      `${snapshot.upcomingFixtures.length} upcoming fixtures, ` +
      `${snapshot.leaders.passing.length} passing leaders, ` +
      `${Object.keys(snapshot.teamSnapshots).length} team snapshots.`
  );
}

main().catch((err) => {
  console.error("NFL snapshot update failed:", err);
  process.exit(1);
});
