import type { TransitSnapshot } from "@/types/bayAreaTransit";

// Auto-generated by scripts/buildBayAreaTransitSnapshot.ts on 2026-06-24T09:51:21.857Z
export const bayAreaTransitSnapshot: TransitSnapshot = {
  "summary": {
    "system": {
      "name": "Bay Area Rapid Transit",
      "abbr": "BART",
      "source": "BART public API (api.bart.gov)",
      "feedTime": "06/24/2026 02:15:32 AM PDT",
      "generatedAt": "2026-06-24T09:51:21.857Z",
      "seed": false
    },
    "heroStats": {
      "lineCount": 6,
      "stationCount": 50,
      "activeAdvisories": 2,
      "elevatorOutages": 1,
      "trainsTracked": 1
    },
    "lines": [
      {
        "id": "daly-city-to-dublin-pleasanton",
        "routeId": "ROUTE 12",
        "name": "Daly City to Dublin/Pleasanton",
        "colorName": "Blue",
        "hexColor": "#0099CC",
        "origin": "DALY",
        "destination": "DUBL",
        "stationCount": 18
      },
      {
        "id": "daly-city-to-berryessa-north-san-jose",
        "routeId": "ROUTE 6",
        "name": "Daly City to Berryessa/North San Jose",
        "colorName": "Green",
        "hexColor": "#FF9933",
        "origin": "DALY",
        "destination": "BERY",
        "stationCount": 22
      },
      {
        "id": "oakland-int-l-airport-oak-to-coliseum",
        "routeId": "ROUTE 19",
        "name": "Oakland Int'l Airport OAK to Coliseum",
        "colorName": "Grey",
        "hexColor": "#FF9933",
        "origin": "OAKL",
        "destination": "OAKL",
        "stationCount": 2
      },
      {
        "id": "berryessa-north-san-jose-to-richmond",
        "routeId": "ROUTE 3",
        "name": "Berryessa/North San Jose to Richmond",
        "colorName": "Orange",
        "hexColor": "#FF0000",
        "origin": "BERY",
        "destination": "RICH",
        "stationCount": 21
      },
      {
        "id": "millbrae-sf-int-l-airport-sfo-to-richmond",
        "routeId": "ROUTE 8",
        "name": "Millbrae/SF Int'l Airport SFO to Richmond",
        "colorName": "Red",
        "hexColor": "#FF0000",
        "origin": "MLBR",
        "destination": "RICH",
        "stationCount": 24
      },
      {
        "id": "millbrae-sf-int-l-sfo-to-antioch",
        "routeId": "ROUTE 2",
        "name": "Millbrae/SF Int'l SFO to Antioch",
        "colorName": "Yellow",
        "hexColor": "#FFFF33",
        "origin": "MLBR",
        "destination": "ANTC",
        "stationCount": 28
      }
    ],
    "stations": [
      {
        "id": "12th",
        "abbr": "12TH",
        "name": "12th St. Oakland City Center",
        "city": "Oakland",
        "latitude": 37.803768,
        "longitude": -122.27145,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "16th",
        "abbr": "16TH",
        "name": "16th St. Mission",
        "city": "San Francisco",
        "latitude": 37.765062,
        "longitude": -122.419694,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "19th",
        "abbr": "19TH",
        "name": "19th St. Oakland",
        "city": "Oakland",
        "latitude": 37.80835,
        "longitude": -122.268602,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "24th",
        "abbr": "24TH",
        "name": "24th St. Mission",
        "city": "San Francisco",
        "latitude": 37.75247,
        "longitude": -122.418143,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "antc",
        "abbr": "ANTC",
        "name": "Antioch",
        "city": "Antioch",
        "latitude": 37.995388,
        "longitude": -121.78042,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "ashb",
        "abbr": "ASHB",
        "name": "Ashby",
        "city": "Berkeley",
        "latitude": 37.852803,
        "longitude": -122.270062,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "balb",
        "abbr": "BALB",
        "name": "Balboa Park",
        "city": "San Francisco",
        "latitude": 37.721585,
        "longitude": -122.447506,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "bayf",
        "abbr": "BAYF",
        "name": "Bay Fair",
        "city": "San Leandro",
        "latitude": 37.696924,
        "longitude": -122.126514,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "bery",
        "abbr": "BERY",
        "name": "Berryessa/North San Jose",
        "city": "San Jose",
        "latitude": 37.368473,
        "longitude": -121.874681,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "cast",
        "abbr": "CAST",
        "name": "Castro Valley",
        "city": "Castro Valley",
        "latitude": 37.690746,
        "longitude": -122.075602,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "civc",
        "abbr": "CIVC",
        "name": "Civic Center/UN Plaza",
        "city": "San Francisco",
        "latitude": 37.779732,
        "longitude": -122.414123,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "cols",
        "abbr": "COLS",
        "name": "Coliseum",
        "city": "Oakland",
        "latitude": 37.753661,
        "longitude": -122.196869,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "colm",
        "abbr": "COLM",
        "name": "Colma",
        "city": "Colma",
        "latitude": 37.684638,
        "longitude": -122.466233,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "conc",
        "abbr": "CONC",
        "name": "Concord",
        "city": "Concord",
        "latitude": 37.973737,
        "longitude": -122.029095,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "daly",
        "abbr": "DALY",
        "name": "Daly City",
        "city": "Daly City",
        "latitude": 37.706121,
        "longitude": -122.469081,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "dbrk",
        "abbr": "DBRK",
        "name": "Downtown Berkeley",
        "city": "Berkeley",
        "latitude": 37.870104,
        "longitude": -122.268133,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "dubl",
        "abbr": "DUBL",
        "name": "Dublin/Pleasanton",
        "city": "Pleasanton",
        "latitude": 37.701687,
        "longitude": -121.899179,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "deln",
        "abbr": "DELN",
        "name": "El Cerrito del Norte",
        "city": "El Cerrito",
        "latitude": 37.925086,
        "longitude": -122.316794,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "plza",
        "abbr": "PLZA",
        "name": "El Cerrito Plaza",
        "city": "El Cerrito",
        "latitude": 37.902632,
        "longitude": -122.298904,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "embr",
        "abbr": "EMBR",
        "name": "Embarcadero",
        "city": "San Francisco",
        "latitude": 37.792874,
        "longitude": -122.39702,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "frmt",
        "abbr": "FRMT",
        "name": "Fremont",
        "city": "Fremont",
        "latitude": 37.557465,
        "longitude": -121.976608,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "ftvl",
        "abbr": "FTVL",
        "name": "Fruitvale",
        "city": "Oakland",
        "latitude": 37.774836,
        "longitude": -122.224175,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "glen",
        "abbr": "GLEN",
        "name": "Glen Park",
        "city": "San Francisco",
        "latitude": 37.733064,
        "longitude": -122.433817,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "hayw",
        "abbr": "HAYW",
        "name": "Hayward",
        "city": "Hayward",
        "latitude": 37.669723,
        "longitude": -122.087018,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "lafy",
        "abbr": "LAFY",
        "name": "Lafayette",
        "city": "Lafayette",
        "latitude": 37.893176,
        "longitude": -122.12463,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "lake",
        "abbr": "LAKE",
        "name": "Lake Merritt",
        "city": "Oakland",
        "latitude": 37.797027,
        "longitude": -122.26518,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "mcar",
        "abbr": "MCAR",
        "name": "MacArthur",
        "city": "Oakland",
        "latitude": 37.829065,
        "longitude": -122.26704,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "mlbr",
        "abbr": "MLBR",
        "name": "Millbrae",
        "city": "Millbrae",
        "latitude": 37.600271,
        "longitude": -122.386702,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "mlpt",
        "abbr": "MLPT",
        "name": "Milpitas",
        "city": "Milpitas",
        "latitude": 37.410277,
        "longitude": -121.891081,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "mont",
        "abbr": "MONT",
        "name": "Montgomery St.",
        "city": "San Francisco",
        "latitude": 37.789405,
        "longitude": -122.401066,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "nbrk",
        "abbr": "NBRK",
        "name": "North Berkeley",
        "city": "Berkeley",
        "latitude": 37.873967,
        "longitude": -122.28344,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "ncon",
        "abbr": "NCON",
        "name": "North Concord/Martinez",
        "city": "Concord",
        "latitude": 38.003193,
        "longitude": -122.024653,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "oakl",
        "abbr": "OAKL",
        "name": "Oakland International Airport",
        "city": "Oakland",
        "latitude": 37.713238,
        "longitude": -122.212191,
        "lines": [
          "Grey"
        ]
      },
      {
        "id": "orin",
        "abbr": "ORIN",
        "name": "Orinda",
        "city": "Orinda",
        "latitude": 37.878361,
        "longitude": -122.183791,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "pctr",
        "abbr": "PCTR",
        "name": "Pittsburg Center",
        "city": "Pittsburg",
        "latitude": 38.016941,
        "longitude": -121.889457,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "pitt",
        "abbr": "PITT",
        "name": "Pittsburg/Bay Point",
        "city": "Pittsburg",
        "latitude": 38.018914,
        "longitude": -121.945154,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "phil",
        "abbr": "PHIL",
        "name": "Pleasant Hill/Contra Costa Centre",
        "city": "Walnut Creek",
        "latitude": 37.928468,
        "longitude": -122.056012,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "powl",
        "abbr": "POWL",
        "name": "Powell St.",
        "city": "San Francisco",
        "latitude": 37.784471,
        "longitude": -122.407974,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "rich",
        "abbr": "RICH",
        "name": "Richmond",
        "city": "Richmond",
        "latitude": 37.936853,
        "longitude": -122.353099,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "rock",
        "abbr": "ROCK",
        "name": "Rockridge",
        "city": "Oakland",
        "latitude": 37.844702,
        "longitude": -122.251371,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "sbrn",
        "abbr": "SBRN",
        "name": "San Bruno",
        "city": "San Bruno",
        "latitude": 37.637761,
        "longitude": -122.416287,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "sfia",
        "abbr": "SFIA",
        "name": "San Francisco International Airport",
        "city": "San Francisco Int'l Airport",
        "latitude": 37.615966,
        "longitude": -122.392409,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "sanl",
        "abbr": "SANL",
        "name": "San Leandro",
        "city": "San Leandro",
        "latitude": 37.721947,
        "longitude": -122.160844,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "shay",
        "abbr": "SHAY",
        "name": "South Hayward",
        "city": "Hayward",
        "latitude": 37.634375,
        "longitude": -122.057189,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "ssan",
        "abbr": "SSAN",
        "name": "South San Francisco",
        "city": "South San Francisco",
        "latitude": 37.664245,
        "longitude": -122.44396,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "ucty",
        "abbr": "UCTY",
        "name": "Union City",
        "city": "Union City",
        "latitude": 37.59063,
        "longitude": -122.017388,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "wcrk",
        "abbr": "WCRK",
        "name": "Walnut Creek",
        "city": "Walnut Creek",
        "latitude": 37.905522,
        "longitude": -122.067527,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "warm",
        "abbr": "WARM",
        "name": "Warm Springs/South Fremont",
        "city": "Fremont",
        "latitude": 37.502171,
        "longitude": -121.939313,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "wdub",
        "abbr": "WDUB",
        "name": "West Dublin/Pleasanton",
        "city": "Dublin",
        "latitude": 37.699756,
        "longitude": -121.92824,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "woak",
        "abbr": "WOAK",
        "name": "West Oakland",
        "city": "Oakland",
        "latitude": 37.804872,
        "longitude": -122.29514,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      }
    ],
    "advisories": [
      {
        "id": "advisory-0",
        "type": "DELAY",
        "description": "Use Tap and Ride to easily pay for BART. At the fare gate, tap your credit/debit card or phone. Each person needs their own card/phone. No transit card/ticket required.",
        "station": "BART",
        "posted": "Thu Jun 11 2026 11:51 AM PDT"
      },
      {
        "id": "advisory-1",
        "type": "DELAY",
        "description": "Expect 30-minute delays starting at 9pm on Sunday-Thursday for riders traveling between Millbrae, SFO, and Daly City stations due to planned train control modernization construction work.",
        "station": "BART",
        "posted": "Mon Jun 22 2026 01:34 AM PDT"
      }
    ],
    "elevator": [
      {
        "id": "elevator-0",
        "description": "There is 1 elevator out of service at this time: RICH: Station",
        "posted": ""
      }
    ],
    "defaultStation": "ncon"
  },
  "stationBoards": {
    "ncon": {
      "id": "ncon",
      "abbr": "NCON",
      "name": "North Concord/Martinez",
      "departures": [
        {
          "destination": "Pittsburg/Bay Point",
          "destinationAbbr": "PITT",
          "minutes": null,
          "platform": "1",
          "direction": "North",
          "length": 10,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-06-24T09:51:21.857Z"
    }
  }
};
