import type { TransitSnapshot } from "@/types/bayAreaTransit";

// Auto-generated by scripts/buildBayAreaTransitSnapshot.ts on 2026-07-12T14:12:55.446Z
export const bayAreaTransitSnapshot: TransitSnapshot = {
  "summary": {
    "system": {
      "name": "Bay Area Rapid Transit",
      "abbr": "BART",
      "source": "BART public API (api.bart.gov)",
      "feedTime": "07/12/2026 07:12:47 AM PDT",
      "generatedAt": "2026-07-12T14:12:55.446Z",
      "seed": false
    },
    "heroStats": {
      "lineCount": 6,
      "stationCount": 50,
      "activeAdvisories": 1,
      "elevatorOutages": 1,
      "trainsTracked": 210
    },
    "lines": [
      {
        "id": "daly-city-to-dublin-pleasanton",
        "routeId": "ROUTE 12",
        "name": "Daly City to Dublin/Pleasanton",
        "colorName": "Blue",
        "hexColor": "#0099CC",
        "origin": "DALY",
        "destination": "DUBL",
        "stationCount": 18
      },
      {
        "id": "daly-city-to-berryessa-north-san-jose",
        "routeId": "ROUTE 6",
        "name": "Daly City to Berryessa/North San Jose",
        "colorName": "Green",
        "hexColor": "#FF9933",
        "origin": "DALY",
        "destination": "BERY",
        "stationCount": 22
      },
      {
        "id": "oakland-int-l-airport-oak-to-coliseum",
        "routeId": "ROUTE 19",
        "name": "Oakland Int'l Airport OAK to Coliseum",
        "colorName": "Grey",
        "hexColor": "#FF9933",
        "origin": "OAKL",
        "destination": "OAKL",
        "stationCount": 2
      },
      {
        "id": "berryessa-north-san-jose-to-richmond",
        "routeId": "ROUTE 3",
        "name": "Berryessa/North San Jose to Richmond",
        "colorName": "Orange",
        "hexColor": "#FF0000",
        "origin": "BERY",
        "destination": "RICH",
        "stationCount": 21
      },
      {
        "id": "millbrae-sf-int-l-airport-sfo-to-richmond",
        "routeId": "ROUTE 8",
        "name": "Millbrae/SF Int'l Airport SFO to Richmond",
        "colorName": "Red",
        "hexColor": "#FF0000",
        "origin": "MLBR",
        "destination": "RICH",
        "stationCount": 24
      },
      {
        "id": "millbrae-sf-int-l-sfo-to-antioch",
        "routeId": "ROUTE 2",
        "name": "Millbrae/SF Int'l SFO to Antioch",
        "colorName": "Yellow",
        "hexColor": "#FFFF33",
        "origin": "MLBR",
        "destination": "ANTC",
        "stationCount": 28
      }
    ],
    "stations": [
      {
        "id": "12th",
        "abbr": "12TH",
        "name": "12th St. Oakland City Center",
        "city": "Oakland",
        "latitude": 37.803768,
        "longitude": -122.27145,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "16th",
        "abbr": "16TH",
        "name": "16th St. Mission",
        "city": "San Francisco",
        "latitude": 37.765062,
        "longitude": -122.419694,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "19th",
        "abbr": "19TH",
        "name": "19th St. Oakland",
        "city": "Oakland",
        "latitude": 37.80835,
        "longitude": -122.268602,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "24th",
        "abbr": "24TH",
        "name": "24th St. Mission",
        "city": "San Francisco",
        "latitude": 37.75247,
        "longitude": -122.418143,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "antc",
        "abbr": "ANTC",
        "name": "Antioch",
        "city": "Antioch",
        "latitude": 37.995388,
        "longitude": -121.78042,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "ashb",
        "abbr": "ASHB",
        "name": "Ashby",
        "city": "Berkeley",
        "latitude": 37.852803,
        "longitude": -122.270062,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "balb",
        "abbr": "BALB",
        "name": "Balboa Park",
        "city": "San Francisco",
        "latitude": 37.721585,
        "longitude": -122.447506,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "bayf",
        "abbr": "BAYF",
        "name": "Bay Fair",
        "city": "San Leandro",
        "latitude": 37.696924,
        "longitude": -122.126514,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "bery",
        "abbr": "BERY",
        "name": "Berryessa/North San Jose",
        "city": "San Jose",
        "latitude": 37.368473,
        "longitude": -121.874681,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "cast",
        "abbr": "CAST",
        "name": "Castro Valley",
        "city": "Castro Valley",
        "latitude": 37.690746,
        "longitude": -122.075602,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "civc",
        "abbr": "CIVC",
        "name": "Civic Center/UN Plaza",
        "city": "San Francisco",
        "latitude": 37.779732,
        "longitude": -122.414123,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "cols",
        "abbr": "COLS",
        "name": "Coliseum",
        "city": "Oakland",
        "latitude": 37.753661,
        "longitude": -122.196869,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "colm",
        "abbr": "COLM",
        "name": "Colma",
        "city": "Colma",
        "latitude": 37.684638,
        "longitude": -122.466233,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "conc",
        "abbr": "CONC",
        "name": "Concord",
        "city": "Concord",
        "latitude": 37.973737,
        "longitude": -122.029095,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "daly",
        "abbr": "DALY",
        "name": "Daly City",
        "city": "Daly City",
        "latitude": 37.706121,
        "longitude": -122.469081,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "dbrk",
        "abbr": "DBRK",
        "name": "Downtown Berkeley",
        "city": "Berkeley",
        "latitude": 37.870104,
        "longitude": -122.268133,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "dubl",
        "abbr": "DUBL",
        "name": "Dublin/Pleasanton",
        "city": "Pleasanton",
        "latitude": 37.701687,
        "longitude": -121.899179,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "deln",
        "abbr": "DELN",
        "name": "El Cerrito del Norte",
        "city": "El Cerrito",
        "latitude": 37.925086,
        "longitude": -122.316794,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "plza",
        "abbr": "PLZA",
        "name": "El Cerrito Plaza",
        "city": "El Cerrito",
        "latitude": 37.902632,
        "longitude": -122.298904,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "embr",
        "abbr": "EMBR",
        "name": "Embarcadero",
        "city": "San Francisco",
        "latitude": 37.792874,
        "longitude": -122.39702,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "frmt",
        "abbr": "FRMT",
        "name": "Fremont",
        "city": "Fremont",
        "latitude": 37.557465,
        "longitude": -121.976608,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "ftvl",
        "abbr": "FTVL",
        "name": "Fruitvale",
        "city": "Oakland",
        "latitude": 37.774836,
        "longitude": -122.224175,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "glen",
        "abbr": "GLEN",
        "name": "Glen Park",
        "city": "San Francisco",
        "latitude": 37.733064,
        "longitude": -122.433817,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "hayw",
        "abbr": "HAYW",
        "name": "Hayward",
        "city": "Hayward",
        "latitude": 37.669723,
        "longitude": -122.087018,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "lafy",
        "abbr": "LAFY",
        "name": "Lafayette",
        "city": "Lafayette",
        "latitude": 37.893176,
        "longitude": -122.12463,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "lake",
        "abbr": "LAKE",
        "name": "Lake Merritt",
        "city": "Oakland",
        "latitude": 37.797027,
        "longitude": -122.26518,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "mcar",
        "abbr": "MCAR",
        "name": "MacArthur",
        "city": "Oakland",
        "latitude": 37.829065,
        "longitude": -122.26704,
        "lines": [
          "Orange",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "mlbr",
        "abbr": "MLBR",
        "name": "Millbrae",
        "city": "Millbrae",
        "latitude": 37.600271,
        "longitude": -122.386702,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "mlpt",
        "abbr": "MLPT",
        "name": "Milpitas",
        "city": "Milpitas",
        "latitude": 37.410277,
        "longitude": -121.891081,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "mont",
        "abbr": "MONT",
        "name": "Montgomery St.",
        "city": "San Francisco",
        "latitude": 37.789405,
        "longitude": -122.401066,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "nbrk",
        "abbr": "NBRK",
        "name": "North Berkeley",
        "city": "Berkeley",
        "latitude": 37.873967,
        "longitude": -122.28344,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "ncon",
        "abbr": "NCON",
        "name": "North Concord/Martinez",
        "city": "Concord",
        "latitude": 38.003193,
        "longitude": -122.024653,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "oakl",
        "abbr": "OAKL",
        "name": "Oakland International Airport",
        "city": "Oakland",
        "latitude": 37.713238,
        "longitude": -122.212191,
        "lines": [
          "Grey"
        ]
      },
      {
        "id": "orin",
        "abbr": "ORIN",
        "name": "Orinda",
        "city": "Orinda",
        "latitude": 37.878361,
        "longitude": -122.183791,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "pctr",
        "abbr": "PCTR",
        "name": "Pittsburg Center",
        "city": "Pittsburg",
        "latitude": 38.016941,
        "longitude": -121.889457,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "pitt",
        "abbr": "PITT",
        "name": "Pittsburg/Bay Point",
        "city": "Pittsburg",
        "latitude": 38.018914,
        "longitude": -121.945154,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "phil",
        "abbr": "PHIL",
        "name": "Pleasant Hill/Contra Costa Centre",
        "city": "Walnut Creek",
        "latitude": 37.928468,
        "longitude": -122.056012,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "powl",
        "abbr": "POWL",
        "name": "Powell St.",
        "city": "San Francisco",
        "latitude": 37.784471,
        "longitude": -122.407974,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "rich",
        "abbr": "RICH",
        "name": "Richmond",
        "city": "Richmond",
        "latitude": 37.936853,
        "longitude": -122.353099,
        "lines": [
          "Orange",
          "Red"
        ]
      },
      {
        "id": "rock",
        "abbr": "ROCK",
        "name": "Rockridge",
        "city": "Oakland",
        "latitude": 37.844702,
        "longitude": -122.251371,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "sbrn",
        "abbr": "SBRN",
        "name": "San Bruno",
        "city": "San Bruno",
        "latitude": 37.637761,
        "longitude": -122.416287,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "sfia",
        "abbr": "SFIA",
        "name": "San Francisco International Airport",
        "city": "San Francisco Int'l Airport",
        "latitude": 37.615966,
        "longitude": -122.392409,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "sanl",
        "abbr": "SANL",
        "name": "San Leandro",
        "city": "San Leandro",
        "latitude": 37.721947,
        "longitude": -122.160844,
        "lines": [
          "Blue",
          "Green",
          "Orange"
        ]
      },
      {
        "id": "shay",
        "abbr": "SHAY",
        "name": "South Hayward",
        "city": "Hayward",
        "latitude": 37.634375,
        "longitude": -122.057189,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "ssan",
        "abbr": "SSAN",
        "name": "South San Francisco",
        "city": "South San Francisco",
        "latitude": 37.664245,
        "longitude": -122.44396,
        "lines": [
          "Red",
          "Yellow"
        ]
      },
      {
        "id": "ucty",
        "abbr": "UCTY",
        "name": "Union City",
        "city": "Union City",
        "latitude": 37.59063,
        "longitude": -122.017388,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "wcrk",
        "abbr": "WCRK",
        "name": "Walnut Creek",
        "city": "Walnut Creek",
        "latitude": 37.905522,
        "longitude": -122.067527,
        "lines": [
          "Yellow"
        ]
      },
      {
        "id": "warm",
        "abbr": "WARM",
        "name": "Warm Springs/South Fremont",
        "city": "Fremont",
        "latitude": 37.502171,
        "longitude": -121.939313,
        "lines": [
          "Green",
          "Orange"
        ]
      },
      {
        "id": "wdub",
        "abbr": "WDUB",
        "name": "West Dublin/Pleasanton",
        "city": "Dublin",
        "latitude": 37.699756,
        "longitude": -121.92824,
        "lines": [
          "Blue"
        ]
      },
      {
        "id": "woak",
        "abbr": "WOAK",
        "name": "West Oakland",
        "city": "Oakland",
        "latitude": 37.804872,
        "longitude": -122.29514,
        "lines": [
          "Blue",
          "Green",
          "Red",
          "Yellow"
        ]
      }
    ],
    "advisories": [
      {
        "id": "advisory-0",
        "type": "DELAY",
        "description": "Use Tap and Ride to easily pay for BART. At the fare gate, tap your credit/debit card or phone. Each person needs their own card/phone. No transit card/ticket required.",
        "station": "BART",
        "posted": "Thu Jun 11 2026 11:51 AM PDT"
      }
    ],
    "elevator": [
      {
        "id": "elevator-0",
        "description": "There are 3 elevators out of service at this time: EMBR: Station; POWL: Station; RICH: Station",
        "posted": ""
      }
    ],
    "defaultStation": "embr"
  },
  "stationBoards": {
    "lake": {
      "id": "lake",
      "abbr": "LAKE",
      "name": "Lake Merritt",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 50,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 60,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 62,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 70,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 77,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 90,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "ftvl": {
      "id": "ftvl",
      "abbr": "FTVL",
      "name": "Fruitvale",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 46,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 56,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 65,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 73,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 74,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 86,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "cols": {
      "id": "cols",
      "abbr": "COLS",
      "name": "Coliseum",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 43,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 53,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 69,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 70,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 77,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 83,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "sanl": {
      "id": "sanl",
      "abbr": "SANL",
      "name": "San Leandro",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 38,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 48,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 65,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 73,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 78,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 81,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "bayf": {
      "id": "bayf",
      "abbr": "BAYF",
      "name": "Bay Fair",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 35,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 45,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 62,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 75,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 77,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 85,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "hayw": {
      "id": "hayw",
      "abbr": "HAYW",
      "name": "Hayward",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 31,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 41,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 71,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 81,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 90,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "shay": {
      "id": "shay",
      "abbr": "SHAY",
      "name": "South Hayward",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 27,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 37,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 67,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 85,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 94,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "ucty": {
      "id": "ucty",
      "abbr": "UCTY",
      "name": "Union City",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 39,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 62,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 91,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 99,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "frmt": {
      "id": "frmt",
      "abbr": "FRMT",
      "name": "Fremont",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 44,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 57,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 95,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 104,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "rock": {
      "id": "rock",
      "abbr": "ROCK",
      "name": "Rockridge",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 47,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 72,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 92,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "orin": {
      "id": "orin",
      "abbr": "ORIN",
      "name": "Orinda",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 41,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 77,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 97,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "lafy": {
      "id": "lafy",
      "abbr": "LAFY",
      "name": "Lafayette",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 36,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 82,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 102,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "wcrk": {
      "id": "wcrk",
      "abbr": "WCRK",
      "name": "Walnut Creek",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 31,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 86,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 106,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "phil": {
      "id": "phil",
      "abbr": "PHIL",
      "name": "Pleasant Hill/Contra Costa Centre",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 28,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 89,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 109,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "conc": {
      "id": "conc",
      "abbr": "CONC",
      "name": "Concord",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 23,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 95,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 115,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "ncon": {
      "id": "ncon",
      "abbr": "NCON",
      "name": "North Concord/Martinez",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 98,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 118,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "pitt": {
      "id": "pitt",
      "abbr": "PITT",
      "name": "Pittsburg/Bay Point",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 105,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 125,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "pctr": {
      "id": "pctr",
      "abbr": "PCTR",
      "name": "Pittsburg Center",
      "departures": [
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 45,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 65,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 85,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "antc": {
      "id": "antc",
      "abbr": "ANTC",
      "name": "Antioch",
      "departures": [
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 38,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 58,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SFO/Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 78,
          "platform": "2",
          "direction": "South",
          "length": 1,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "12th": {
      "id": "12th",
      "abbr": "12TH",
      "name": "12th St. Oakland City Center",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 56,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 58,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 63,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 63,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 63,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 83,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "19th": {
      "id": "19th",
      "abbr": "19TH",
      "name": "19th St. Oakland",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 54,
          "platform": "2",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 56,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 61,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 65,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 65,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 85,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "mcar": {
      "id": "mcar",
      "abbr": "MCAR",
      "name": "MacArthur",
      "departures": [
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 50,
          "platform": "4",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 53,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 57,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 69,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 69,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 89,
          "platform": "3",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "cast": {
      "id": "cast",
      "abbr": "CAST",
      "name": "Castro Valley",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 57,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "wdub": {
      "id": "wdub",
      "abbr": "WDUB",
      "name": "West Dublin/Pleasanton",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 47,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "dubl": {
      "id": "dubl",
      "abbr": "DUBL",
      "name": "Dublin/Pleasanton",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 44,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "woak": {
      "id": "woak",
      "abbr": "WOAK",
      "name": "West Oakland",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 56,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 59,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 61,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 64,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 67,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 79,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 83,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 96,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "embr": {
      "id": "embr",
      "abbr": "EMBR",
      "name": "Embarcadero",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 52,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 57,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 63,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 68,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 72,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 74,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 90,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 103,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "mont": {
      "id": "mont",
      "abbr": "MONT",
      "name": "Montgomery St.",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 50,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 55,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 65,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 69,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 70,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 76,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 92,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 105,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "powl": {
      "id": "powl",
      "abbr": "POWL",
      "name": "Powell St.",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 48,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 54,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 66,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 68,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 71,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 78,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 93,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 106,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "civc": {
      "id": "civc",
      "abbr": "CIVC",
      "name": "Civic Center/UN Plaza",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 47,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 52,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 67,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 68,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 72,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 79,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 95,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 108,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "16th": {
      "id": "16th",
      "abbr": "16TH",
      "name": "16th St. Mission",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 44,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 50,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 64,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 70,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 75,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 82,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 97,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 110,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "24th": {
      "id": "24th",
      "abbr": "24TH",
      "name": "24th St. Mission",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 42,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 48,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 62,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 72,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 77,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 84,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 99,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 112,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "glen": {
      "id": "glen",
      "abbr": "GLEN",
      "name": "Glen Park",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 39,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 45,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 59,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 75,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 80,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 86,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 102,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 115,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "balb": {
      "id": "balb",
      "abbr": "BALB",
      "name": "Balboa Park",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 37,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 43,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 57,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 77,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 82,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 89,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 104,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "BLUE",
          "hexColor": "#0099cc",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 117,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "daly": {
      "id": "daly",
      "abbr": "DALY",
      "name": "Daly City",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 33,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 39,
          "platform": "2",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 53,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 86,
          "platform": "3",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 93,
          "platform": "3",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "ashb": {
      "id": "ashb",
      "abbr": "ASHB",
      "name": "Ashby",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 47,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 53,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 72,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "dbrk": {
      "id": "dbrk",
      "abbr": "DBRK",
      "name": "Downtown Berkeley",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 44,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 51,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 75,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "nbrk": {
      "id": "nbrk",
      "abbr": "NBRK",
      "name": "North Berkeley",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 42,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 49,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 77,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "plza": {
      "id": "plza",
      "abbr": "PLZA",
      "name": "El Cerrito Plaza",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 38,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 45,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 80,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "deln": {
      "id": "deln",
      "abbr": "DELN",
      "name": "El Cerrito del Norte",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 35,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 42,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Richmond",
          "destinationAbbr": "RICH",
          "minutes": 84,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "rich": {
      "id": "rich",
      "abbr": "RICH",
      "name": "Richmond",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 31,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 38,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "warm": {
      "id": "warm",
      "abbr": "WARM",
      "name": "Warm Springs/South Fremont",
      "departures": [
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 50,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 51,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 101,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 110,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "mlpt": {
      "id": "mlpt",
      "abbr": "MLPT",
      "name": "Milpitas",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 43,
          "platform": "2",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 57,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 109,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "ORANGE",
          "hexColor": "#ff9933",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Berryessa",
          "destinationAbbr": "BERY",
          "minutes": 117,
          "platform": "1",
          "direction": "North",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "bery": {
      "id": "bery",
      "abbr": "BERY",
      "name": "Berryessa/North San Jose",
      "departures": [
        {
          "destination": "Daly City",
          "destinationAbbr": "DALY",
          "minutes": 39,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "GREEN",
          "hexColor": "#339933",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "colm": {
      "id": "colm",
      "abbr": "COLM",
      "name": "Colma",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 50,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 90,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 97,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "ssan": {
      "id": "ssan",
      "abbr": "SSAN",
      "name": "South San Francisco",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 46,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 93,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 100,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "sbrn": {
      "id": "sbrn",
      "abbr": "SBRN",
      "name": "San Bruno",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 43,
          "platform": "2",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "SF Airport",
          "destinationAbbr": "SFIA",
          "minutes": 97,
          "platform": "1",
          "direction": "South",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        },
        {
          "destination": "Millbrae",
          "destinationAbbr": "MLBR",
          "minutes": 103,
          "platform": "1",
          "direction": "South",
          "length": 6,
          "colorName": "RED",
          "hexColor": "#ff0000",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    },
    "sfia": {
      "id": "sfia",
      "abbr": "SFIA",
      "name": "San Francisco Int'l Airport",
      "departures": [
        {
          "destination": "Antioch",
          "destinationAbbr": "ANTC",
          "minutes": 39,
          "platform": "1",
          "direction": "North",
          "length": 9,
          "colorName": "YELLOW",
          "hexColor": "#ffff33",
          "delaySeconds": 0,
          "bikesAllowed": true
        }
      ],
      "generatedAt": "2026-07-12T14:12:55.446Z"
    }
  }
};
