import type { GolfSnapshot } from "@/types/golf";

// Auto-generated by scripts/buildGolfSnapshot.ts on 2026-08-15T19:00:02.673Z
export const golfSnapshot: GolfSnapshot = {
  "summary": {
    "tournament": {
      "id": "wgc-bridgestone-invitational-2026",
      "name": "WGC-Bridgestone Invitational",
      "tour": "PGA TOUR",
      "course": "TPC Southwind",
      "coursePar": 70,
      "location": "Memphis, TN, USA",
      "startDate": "",
      "endDate": "2026-08-16",
      "roundLabel": "Round 3",
      "status": "Round 3 - In Progress",
      "fieldSize": 69,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "heroStats": {
      "leaderName": "Viktor Hovland",
      "leaderScore": -10,
      "playersUnderPar": 42,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "fieldSize": 69
    },
    "leaderboard": [
      {
        "playerId": "viktor-hovland",
        "playerName": "Viktor Hovland",
        "country": "Norway",
        "position": "T1",
        "totalToPar": -10,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "roundScores": [
          68,
          64,
          18
        ],
        "movement": -1
      },
      {
        "playerId": "scottie-scheffler",
        "playerName": "Scottie Scheffler",
        "country": "USA",
        "position": "T1",
        "totalToPar": -10,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "roundScores": [
          68,
          61,
          21
        ],
        "movement": 0
      },
      {
        "playerId": "sam-burns",
        "playerName": "Sam Burns",
        "country": "USA",
        "position": "3",
        "totalToPar": -9,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "roundScores": [
          67,
          70,
          40
        ],
        "movement": -16
      },
      {
        "playerId": "sungjae-im",
        "playerName": "Sungjae Im",
        "country": "South Korea",
        "position": "4",
        "totalToPar": -8,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "roundScores": [
          66,
          66,
          20
        ],
        "movement": 2
      },
      {
        "playerId": "kurt-kitayama",
        "playerName": "Kurt Kitayama",
        "country": "USA",
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          65,
          73,
          57
        ],
        "movement": -22
      },
      {
        "playerId": "ludvig-aberg",
        "playerName": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "roundScores": [
          68,
          65,
          20
        ],
        "movement": 1
      },
      {
        "playerId": "tommy-fleetwood",
        "playerName": "Tommy Fleetwood",
        "country": "England",
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "6",
        "status": "In Progress",
        "roundScores": [
          66,
          68,
          23
        ],
        "movement": 0
      },
      {
        "playerId": "si-woo-kim",
        "playerName": "Si Woo Kim",
        "country": "South Korea",
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          70,
          68,
          61
        ],
        "movement": -22
      },
      {
        "playerId": "jake-knapp",
        "playerName": "Jake Knapp",
        "country": "USA",
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "roundScores": [
          65,
          70,
          33
        ],
        "movement": -4
      },
      {
        "playerId": "tom-kim",
        "playerName": "Tom Kim",
        "country": "South Korea",
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69,
          72,
          63
        ],
        "movement": -35
      },
      {
        "playerId": "chris-gotterup",
        "playerName": "Chris Gotterup",
        "country": "USA",
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "roundScores": [
          66,
          70,
          33
        ],
        "movement": -4
      },
      {
        "playerId": "hideki-matsuyama",
        "playerName": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "11",
        "status": "In Progress",
        "roundScores": [
          66,
          70,
          40
        ],
        "movement": -4
      },
      {
        "playerId": "j-t-poston",
        "playerName": "J.T. Poston",
        "country": "USA",
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          68,
          66
        ],
        "movement": -21
      },
      {
        "playerId": "brian-harman",
        "playerName": "Brian Harman",
        "country": "USA",
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "7",
        "status": "In Progress",
        "roundScores": [
          70,
          64,
          29
        ],
        "movement": 8
      },
      {
        "playerId": "alex-noren",
        "playerName": "Alex Noren",
        "country": "Sweden",
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "roundScores": [
          71,
          66,
          48
        ],
        "movement": -6
      },
      {
        "playerId": "jordan-spieth",
        "playerName": "Jordan Spieth",
        "country": "USA",
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "7",
        "status": "In Progress",
        "roundScores": [
          65,
          69,
          29
        ],
        "movement": 8
      },
      {
        "playerId": "patrick-cantlay",
        "playerName": "Patrick Cantlay",
        "country": "USA",
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "roundScores": [
          69,
          66,
          35
        ],
        "movement": 4
      },
      {
        "playerId": "wyndham-clark",
        "playerName": "Wyndham Clark",
        "country": "USA",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "roundScores": [
          69,
          66,
          36
        ],
        "movement": 9
      },
      {
        "playerId": "gary-woodland",
        "playerName": "Gary Woodland",
        "country": "USA",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "roundScores": [
          66,
          71,
          52
        ],
        "movement": -1
      },
      {
        "playerId": "adam-scott",
        "playerName": "Adam Scott",
        "country": "Australia",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "10",
        "status": "In Progress",
        "roundScores": [
          66,
          70,
          39
        ],
        "movement": 4
      },
      {
        "playerId": "nico-echavarria",
        "playerName": "Nico Echavarria",
        "country": "Colombia",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "6",
        "status": "In Progress",
        "roundScores": [
          68,
          66,
          26
        ],
        "movement": 13
      },
      {
        "playerId": "patrick-rodgers",
        "playerName": "Patrick Rodgers",
        "country": "USA",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "10",
        "status": "In Progress",
        "roundScores": [
          67,
          69,
          39
        ],
        "movement": 4
      },
      {
        "playerId": "matt-fitzpatrick",
        "playerName": "Matt Fitzpatrick",
        "country": "England",
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "roundScores": [
          70,
          67,
          45
        ],
        "movement": -1
      },
      {
        "playerId": "xander-schauffele",
        "playerName": "Xander Schauffele",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67,
          72,
          68
        ],
        "movement": -10
      },
      {
        "playerId": "j-j-spaun",
        "playerName": "J.J. Spaun",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          69,
          67
        ],
        "movement": -14
      },
      {
        "playerId": "rickie-fowler",
        "playerName": "Rickie Fowler",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68,
          73,
          66
        ],
        "movement": -21
      },
      {
        "playerId": "cameron-young",
        "playerName": "Cameron Young",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          69,
          69,
          61
        ],
        "movement": -3
      },
      {
        "playerId": "pierceson-coody",
        "playerName": "Pierceson Coody",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "roundScores": [
          71,
          66,
          50
        ],
        "movement": 5
      },
      {
        "playerId": "jacob-bridgeman",
        "playerName": "Jacob Bridgeman",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          69,
          70,
          64
        ],
        "movement": -10
      },
      {
        "playerId": "jackson-koivun",
        "playerName": "Jackson Koivun",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          70,
          66
        ],
        "movement": -21
      },
      {
        "playerId": "keith-mitchell",
        "playerName": "Keith Mitchell",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "8",
        "status": "In Progress",
        "roundScores": [
          69,
          66,
          33
        ],
        "movement": 15
      },
      {
        "playerId": "alex-smalley",
        "playerName": "Alex Smalley",
        "country": "USA",
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "11",
        "status": "In Progress",
        "roundScores": [
          68,
          68,
          43
        ],
        "movement": 10
      },
      {
        "playerId": "nick-taylor",
        "playerName": "Nick Taylor",
        "country": "Canada",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "roundScores": [
          69,
          68,
          47
        ],
        "movement": 14
      },
      {
        "playerId": "harry-hall",
        "playerName": "Harry Hall",
        "country": "England",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72,
          68,
          68
        ],
        "movement": -5
      },
      {
        "playerId": "ryan-gerard",
        "playerName": "Ryan Gerard",
        "country": "USA",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          70,
          70,
          68
        ],
        "movement": -5
      },
      {
        "playerId": "sudarshan-yellamaraju",
        "playerName": "Sudarshan Yellamaraju",
        "country": "Canada",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "8",
        "status": "In Progress",
        "roundScores": [
          70,
          65,
          34
        ],
        "movement": 24
      },
      {
        "playerId": "russell-henley",
        "playerName": "Russell Henley",
        "country": "USA",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          70,
          67
        ],
        "movement": -12
      },
      {
        "playerId": "maverick-mcnealy",
        "playerName": "Maverick McNealy",
        "country": "USA",
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          68,
          70,
          62
        ],
        "movement": 6
      },
      {
        "playerId": "aaron-rai",
        "playerName": "Aaron Rai",
        "country": "England",
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          72,
          66,
          63
        ],
        "movement": 12
      },
      {
        "playerId": "bud-cauley",
        "playerName": "Bud Cauley",
        "country": "USA",
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "roundScores": [
          66,
          72,
          58
        ],
        "movement": 12
      },
      {
        "playerId": "max-homa",
        "playerName": "Max Homa",
        "country": "USA",
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          67,
          69
        ],
        "movement": 1
      },
      {
        "playerId": "michael-kim",
        "playerName": "Michael Kim",
        "country": "USA",
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "roundScores": [
          65,
          72,
          48
        ],
        "movement": 20
      },
      {
        "playerId": "sam-stevens",
        "playerName": "Sam Stevens",
        "country": "USA",
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69,
          71,
          70
        ],
        "movement": 5
      },
      {
        "playerId": "matti-schmid",
        "playerName": "Matti Schmid",
        "country": "Germany",
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          70,
          67
        ],
        "movement": -11
      },
      {
        "playerId": "justin-thomas",
        "playerName": "Justin Thomas",
        "country": "USA",
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "roundScores": [
          70,
          67,
          56
        ],
        "movement": 24
      },
      {
        "playerId": "ryo-hisatsune",
        "playerName": "Ryo Hisatsune",
        "country": "Japan",
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69,
          70,
          71
        ],
        "movement": 9
      },
      {
        "playerId": "michael-brennan",
        "playerName": "Michael Brennan",
        "country": "USA",
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          70,
          67
        ],
        "movement": -11
      },
      {
        "playerId": "collin-morikawa",
        "playerName": "Collin Morikawa",
        "country": "USA",
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          69,
          71
        ],
        "movement": 10
      },
      {
        "playerId": "nicolai-h-jgaard",
        "playerName": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          70,
          68
        ],
        "movement": -6
      },
      {
        "playerId": "jordan-smith",
        "playerName": "Jordan Smith",
        "country": "England",
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          73,
          67
        ],
        "movement": -12
      },
      {
        "playerId": "min-woo-lee",
        "playerName": "Min Woo Lee",
        "country": "Australia",
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "roundScores": [
          67,
          71,
          61
        ],
        "movement": 24
      },
      {
        "playerId": "michael-thorbjornsen",
        "playerName": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          65,
          75,
          72
        ],
        "movement": 13
      },
      {
        "playerId": "corey-conners",
        "playerName": "Corey Conners",
        "country": "Canada",
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          71,
          70
        ],
        "movement": -1
      },
      {
        "playerId": "ben-griffin",
        "playerName": "Ben Griffin",
        "country": "USA",
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          71,
          69
        ],
        "movement": -6
      },
      {
        "playerId": "shane-lowry",
        "playerName": "Shane Lowry",
        "country": "Ireland",
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69,
          72,
          72
        ],
        "movement": 9
      },
      {
        "playerId": "sepp-straka",
        "playerName": "Sepp Straka",
        "country": "Austria",
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68,
          73,
          72
        ],
        "movement": 9
      },
      {
        "playerId": "eric-cole",
        "playerName": "Eric Cole",
        "country": "USA",
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72,
          72,
          70
        ],
        "movement": -3
      },
      {
        "playerId": "ricky-castillo",
        "playerName": "Ricky Castillo",
        "country": "USA",
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72,
          74,
          68
        ],
        "movement": -10
      },
      {
        "playerId": "aldrich-potgieter",
        "playerName": "Aldrich Potgieter",
        "country": "South Africa",
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          71,
          72
        ],
        "movement": 5
      },
      {
        "playerId": "harris-english",
        "playerName": "Harris English",
        "country": "USA",
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68,
          75,
          71
        ],
        "movement": 3
      },
      {
        "playerId": "alex-fitzpatrick",
        "playerName": "Alex Fitzpatrick",
        "country": "England",
        "position": "61",
        "totalToPar": 5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71,
          74,
          70
        ],
        "movement": -4
      },
      {
        "playerId": "rory-mcilroy",
        "playerName": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          74,
          70,
          72
        ],
        "movement": 2
      },
      {
        "playerId": "kristoffer-reitan",
        "playerName": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72,
          71,
          73
        ],
        "movement": 8
      },
      {
        "playerId": "matt-mccarty",
        "playerName": "Matt McCarty",
        "country": "USA",
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          72,
          71
        ],
        "movement": -3
      },
      {
        "playerId": "justin-rose",
        "playerName": "Justin Rose",
        "country": "England",
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          70,
          73
        ],
        "movement": 8
      },
      {
        "playerId": "akshay-bhatia",
        "playerName": "Akshay Bhatia",
        "country": "USA",
        "position": "66",
        "totalToPar": 7,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72,
          72,
          73
        ],
        "movement": 6
      },
      {
        "playerId": "ryan-fox",
        "playerName": "Ryan Fox",
        "country": "New Zealand",
        "position": "67",
        "totalToPar": 8,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73,
          73,
          72
        ],
        "movement": 0
      },
      {
        "playerId": "sahith-theegala",
        "playerName": "Sahith Theegala",
        "country": "USA",
        "position": "68",
        "totalToPar": 10,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69,
          72,
          79
        ],
        "movement": 23
      },
      {
        "playerId": "robert-macintyre",
        "playerName": "Robert MacIntyre",
        "country": "Scotland",
        "position": "-",
        "totalToPar": 12,
        "today": 0,
        "thru": "F",
        "status": "Withdrawn",
        "roundScores": [
          82
        ],
        "movement": 0
      }
    ],
    "players": [
      {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA",
        "position": "T5"
      },
      {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA",
        "position": "T57"
      },
      {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA",
        "position": "T48"
      },
      {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England",
        "position": "T39"
      },
      {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA",
        "position": "68"
      },
      {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA",
        "position": "T18"
      },
      {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T48"
      },
      {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland",
        "position": "-"
      },
      {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea",
        "position": "4"
      },
      {
        "id": "brian-harman",
        "name": "Brian Harman",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "T62"
      },
      {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA",
        "position": "T18"
      },
      {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "nick-taylor",
        "name": "Nick Taylor",
        "country": "Canada",
        "position": "T33"
      },
      {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden",
        "position": "T13"
      },
      {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia",
        "position": "T18"
      },
      {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand",
        "position": "67"
      },
      {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T62"
      },
      {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England",
        "position": "61"
      },
      {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway",
        "position": "T1"
      },
      {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T5"
      },
      {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA",
        "position": "T54"
      },
      {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia",
        "position": "T18"
      },
      {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia",
        "position": "T51"
      },
      {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA",
        "position": "66"
      },
      {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T51"
      },
      {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "sam-stevens",
        "name": "Sam Stevens",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "matti-schmid",
        "name": "Matti Schmid",
        "country": "Germany",
        "position": "T43"
      },
      {
        "id": "shane-lowry",
        "name": "Shane Lowry",
        "country": "Ireland",
        "position": "T54"
      },
      {
        "id": "harry-hall",
        "name": "Harry Hall",
        "country": "England",
        "position": "T33"
      },
      {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea",
        "position": "T10"
      },
      {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "ricky-castillo",
        "name": "Ricky Castillo",
        "country": "USA",
        "position": "T57"
      },
      {
        "id": "pierceson-coody",
        "name": "Pierceson Coody",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan",
        "position": "T43"
      },
      {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA",
        "position": "T62"
      },
      {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA",
        "position": "T33"
      },
      {
        "id": "aldrich-potgieter",
        "name": "Aldrich Potgieter",
        "country": "South Africa",
        "position": "T57"
      },
      {
        "id": "sudarshan-yellamaraju",
        "name": "Sudarshan Yellamaraju",
        "country": "Canada",
        "position": "T33"
      },
      {
        "id": "jackson-koivun",
        "name": "Jackson Koivun",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA",
        "position": "T39"
      },
      {
        "id": "harris-english",
        "name": "Harris English",
        "country": "USA",
        "position": "T57"
      },
      {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA",
        "position": "T33"
      },
      {
        "id": "jordan-spieth",
        "name": "Jordan Spieth",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England",
        "position": "T5"
      },
      {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England",
        "position": "T62"
      },
      {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T10"
      },
      {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "patrick-rodgers",
        "name": "Patrick Rodgers",
        "country": "USA",
        "position": "T18"
      },
      {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea",
        "position": "T5"
      },
      {
        "id": "keith-mitchell",
        "name": "Keith Mitchell",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria",
        "position": "T54"
      },
      {
        "id": "max-homa",
        "name": "Max Homa",
        "country": "USA",
        "position": "T39"
      },
      {
        "id": "michael-kim",
        "name": "Michael Kim",
        "country": "USA",
        "position": "T39"
      },
      {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England",
        "position": "T18"
      },
      {
        "id": "corey-conners",
        "name": "Corey Conners",
        "country": "Canada",
        "position": "T51"
      },
      {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA",
        "position": "T24"
      },
      {
        "id": "jordan-smith",
        "name": "Jordan Smith",
        "country": "England",
        "position": "T48"
      },
      {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA",
        "position": "T33"
      },
      {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA",
        "position": "T5"
      },
      {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA",
        "position": "3"
      }
    ]
  },
  "playerSnapshots": {
    "xander-schauffele": {
      "player": {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -10,
        "nextTeeTime": "10:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "j-j-spaun": {
      "player": {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -14,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 3,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "kurt-kitayama": {
      "player": {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": -22,
        "nextTeeTime": "11:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 2,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 3,
          "score": 57,
          "relativeToPar": -13
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "j-t-poston": {
      "player": {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -21,
        "nextTeeTime": "10:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "eric-cole": {
      "player": {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -3,
        "nextTeeTime": "8:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "collin-morikawa": {
      "player": {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 10,
        "nextTeeTime": "10:15 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 3,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "aaron-rai": {
      "player": {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": 12,
        "nextTeeTime": "11:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 63,
          "relativeToPar": -7
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sahith-theegala": {
      "player": {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "68",
        "totalToPar": 10,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 23,
        "nextTeeTime": "9:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 79,
          "relativeToPar": 9
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "wyndham-clark": {
      "player": {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "movement": 9,
        "nextTeeTime": "12:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 36,
          "relativeToPar": -34
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "nicolai-h-jgaard": {
      "player": {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -6,
        "nextTeeTime": "8:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "robert-macintyre": {
      "player": {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland"
      },
      "tournamentStatus": {
        "position": "-",
        "totalToPar": 12,
        "today": 0,
        "thru": "F",
        "status": "Withdrawn",
        "movement": 0,
        "nextTeeTime": null
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 82,
          "relativeToPar": 12
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sungjae-im": {
      "player": {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "4",
        "totalToPar": -8,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "movement": 2,
        "nextTeeTime": "1:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 20,
          "relativeToPar": -50
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "brian-harman": {
      "player": {
        "id": "brian-harman",
        "name": "Brian Harman",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "7",
        "status": "In Progress",
        "movement": 8,
        "nextTeeTime": "1:15 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 64,
          "relativeToPar": -6
        },
        {
          "round": 3,
          "score": 29,
          "relativeToPar": -41
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "rory-mcilroy": {
      "player": {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland"
      },
      "tournamentStatus": {
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 2,
        "nextTeeTime": "8:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 74,
          "relativeToPar": 4
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "gary-woodland": {
      "player": {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "movement": -1,
        "nextTeeTime": "11:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 52,
          "relativeToPar": -18
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "rickie-fowler": {
      "player": {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -21,
        "nextTeeTime": "9:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 3,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "nick-taylor": {
      "player": {
        "id": "nick-taylor",
        "name": "Nick Taylor",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "movement": 14,
        "nextTeeTime": "12:00 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 47,
          "relativeToPar": -23
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "alex-noren": {
      "player": {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "movement": -6,
        "nextTeeTime": "11:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 48,
          "relativeToPar": -22
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "adam-scott": {
      "player": {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "10",
        "status": "In Progress",
        "movement": 4,
        "nextTeeTime": "12:30 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 39,
          "relativeToPar": -31
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ryan-fox": {
      "player": {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand"
      },
      "tournamentStatus": {
        "position": "67",
        "totalToPar": 8,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "8:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "kristoffer-reitan": {
      "player": {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 8,
        "nextTeeTime": "8:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "alex-fitzpatrick": {
      "player": {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "61",
        "totalToPar": 5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -4,
        "nextTeeTime": "8:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 74,
          "relativeToPar": 4
        },
        {
          "round": 3,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "viktor-hovland": {
      "player": {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -10,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "movement": -1,
        "nextTeeTime": "1:35 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 64,
          "relativeToPar": -6
        },
        {
          "round": 3,
          "score": 18,
          "relativeToPar": -52
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ludvig-aberg": {
      "player": {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "movement": 1,
        "nextTeeTime": "1:35 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 3,
          "score": 20,
          "relativeToPar": -50
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ben-griffin": {
      "player": {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -6,
        "nextTeeTime": "8:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "nico-echavarria": {
      "player": {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "6",
        "status": "In Progress",
        "movement": 13,
        "nextTeeTime": "1:25 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 26,
          "relativeToPar": -44
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "min-woo-lee": {
      "player": {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "movement": 24,
        "nextTeeTime": "11:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 61,
          "relativeToPar": -9
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "akshay-bhatia": {
      "player": {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "66",
        "totalToPar": 7,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 6,
        "nextTeeTime": "8:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "michael-thorbjornsen": {
      "player": {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 13,
        "nextTeeTime": "10:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 2,
          "score": 75,
          "relativeToPar": 5
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "cameron-young": {
      "player": {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": -3,
        "nextTeeTime": "11:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 3,
          "score": 61,
          "relativeToPar": -9
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sam-stevens": {
      "player": {
        "id": "sam-stevens",
        "name": "Sam Stevens",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 5,
        "nextTeeTime": "10:15 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "matti-schmid": {
      "player": {
        "id": "matti-schmid",
        "name": "Matti Schmid",
        "country": "Germany"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -11,
        "nextTeeTime": "8:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "shane-lowry": {
      "player": {
        "id": "shane-lowry",
        "name": "Shane Lowry",
        "country": "Ireland"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 9,
        "nextTeeTime": "9:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "harry-hall": {
      "player": {
        "id": "harry-hall",
        "name": "Harry Hall",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -5,
        "nextTeeTime": "10:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "tom-kim": {
      "player": {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -35,
        "nextTeeTime": "9:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 63,
          "relativeToPar": -7
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "chris-gotterup": {
      "player": {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "movement": -4,
        "nextTeeTime": "12:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 33,
          "relativeToPar": -37
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ricky-castillo": {
      "player": {
        "id": "ricky-castillo",
        "name": "Ricky Castillo",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -10,
        "nextTeeTime": "8:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 2,
          "score": 74,
          "relativeToPar": 4
        },
        {
          "round": 3,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "pierceson-coody": {
      "player": {
        "id": "pierceson-coody",
        "name": "Pierceson Coody",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "movement": 5,
        "nextTeeTime": "11:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 50,
          "relativeToPar": -20
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "justin-thomas": {
      "player": {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "movement": 24,
        "nextTeeTime": "11:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 3,
          "score": 56,
          "relativeToPar": -14
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ryo-hisatsune": {
      "player": {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 9,
        "nextTeeTime": "10:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "matt-mccarty": {
      "player": {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -3,
        "nextTeeTime": "8:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "michael-brennan": {
      "player": {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -11,
        "nextTeeTime": "9:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "jacob-bridgeman": {
      "player": {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": -10,
        "nextTeeTime": "10:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 64,
          "relativeToPar": -6
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "ryan-gerard": {
      "player": {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -5,
        "nextTeeTime": "10:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "aldrich-potgieter": {
      "player": {
        "id": "aldrich-potgieter",
        "name": "Aldrich Potgieter",
        "country": "South Africa"
      },
      "tournamentStatus": {
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 5,
        "nextTeeTime": "9:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sudarshan-yellamaraju": {
      "player": {
        "id": "sudarshan-yellamaraju",
        "name": "Sudarshan Yellamaraju",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "8",
        "status": "In Progress",
        "movement": 24,
        "nextTeeTime": "1:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 3,
          "score": 34,
          "relativeToPar": -36
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "jackson-koivun": {
      "player": {
        "id": "jackson-koivun",
        "name": "Jackson Koivun",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -21,
        "nextTeeTime": "9:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "bud-cauley": {
      "player": {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "movement": 12,
        "nextTeeTime": "11:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 58,
          "relativeToPar": -12
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "harris-english": {
      "player": {
        "id": "harris-english",
        "name": "Harris English",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T57",
        "totalToPar": 4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 3,
        "nextTeeTime": "9:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 75,
          "relativeToPar": 5
        },
        {
          "round": 3,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "russell-henley": {
      "player": {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -12,
        "nextTeeTime": "9:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "jordan-spieth": {
      "player": {
        "id": "jordan-spieth",
        "name": "Jordan Spieth",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "7",
        "status": "In Progress",
        "movement": 8,
        "nextTeeTime": "1:15 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 2,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 3,
          "score": 29,
          "relativeToPar": -41
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "tommy-fleetwood": {
      "player": {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "6",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "1:25 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 23,
          "relativeToPar": -47
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "justin-rose": {
      "player": {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T62",
        "totalToPar": 6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 8,
        "nextTeeTime": "9:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "hideki-matsuyama": {
      "player": {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -6,
        "today": 0,
        "thru": "11",
        "status": "In Progress",
        "movement": -4,
        "nextTeeTime": "12:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 40,
          "relativeToPar": -30
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "patrick-cantlay": {
      "player": {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -5,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "movement": 4,
        "nextTeeTime": "12:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 35,
          "relativeToPar": -35
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "patrick-rodgers": {
      "player": {
        "id": "patrick-rodgers",
        "name": "Patrick Rodgers",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "10",
        "status": "In Progress",
        "movement": 4,
        "nextTeeTime": "12:30 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 2,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 3,
          "score": 39,
          "relativeToPar": -31
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "si-woo-kim": {
      "player": {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": -22,
        "nextTeeTime": "10:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 61,
          "relativeToPar": -9
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "keith-mitchell": {
      "player": {
        "id": "keith-mitchell",
        "name": "Keith Mitchell",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "8",
        "status": "In Progress",
        "movement": 15,
        "nextTeeTime": "1:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        },
        {
          "round": 2,
          "score": 66,
          "relativeToPar": -4
        },
        {
          "round": 3,
          "score": 33,
          "relativeToPar": -37
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sepp-straka": {
      "player": {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 9,
        "nextTeeTime": "9:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 3,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "max-homa": {
      "player": {
        "id": "max-homa",
        "name": "Max Homa",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 1,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 2,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 3,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "michael-kim": {
      "player": {
        "id": "michael-kim",
        "name": "Michael Kim",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T39",
        "totalToPar": -1,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "movement": 20,
        "nextTeeTime": "12:00 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 2,
          "score": 72,
          "relativeToPar": 2
        },
        {
          "round": 3,
          "score": 48,
          "relativeToPar": -22
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "matt-fitzpatrick": {
      "player": {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T18",
        "totalToPar": -4,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "movement": -1,
        "nextTeeTime": "12:10 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 2,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 3,
          "score": 45,
          "relativeToPar": -25
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "corey-conners": {
      "player": {
        "id": "corey-conners",
        "name": "Corey Conners",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T51",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -1,
        "nextTeeTime": "9:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 3,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "scottie-scheffler": {
      "player": {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -10,
        "today": 0,
        "thru": "5",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "1:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 61,
          "relativeToPar": -9
        },
        {
          "round": 3,
          "score": 21,
          "relativeToPar": -49
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "alex-smalley": {
      "player": {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T24",
        "totalToPar": -3,
        "today": 0,
        "thru": "11",
        "status": "In Progress",
        "movement": 10,
        "nextTeeTime": "12:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 3,
          "score": 43,
          "relativeToPar": -27
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "jordan-smith": {
      "player": {
        "id": "jordan-smith",
        "name": "Jordan Smith",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": -12,
        "nextTeeTime": "8:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        },
        {
          "round": 2,
          "score": 73,
          "relativeToPar": 3
        },
        {
          "round": 3,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "maverick-mcnealy": {
      "player": {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T33",
        "totalToPar": -2,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": 6,
        "nextTeeTime": "11:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 62,
          "relativeToPar": -8
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "jake-knapp": {
      "player": {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T5",
        "totalToPar": -7,
        "today": 0,
        "thru": "9",
        "status": "In Progress",
        "movement": -4,
        "nextTeeTime": "12:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 33,
          "relativeToPar": -37
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    },
    "sam-burns": {
      "player": {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "3",
        "totalToPar": -9,
        "today": 0,
        "thru": "12",
        "status": "In Progress",
        "movement": -16,
        "nextTeeTime": "12:10 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        },
        {
          "round": 2,
          "score": 70,
          "relativeToPar": 0
        },
        {
          "round": 3,
          "score": 40,
          "relativeToPar": -30
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-15T19:00:02.673Z"
    }
  }
};
