import type { GolfSnapshot } from "@/types/golf";

// Auto-generated by scripts/buildGolfSnapshot.ts on 2026-08-20T21:56:59.763Z
export const golfSnapshot: GolfSnapshot = {
  "summary": {
    "tournament": {
      "id": "bmw-championship-2026",
      "name": "BMW Championship",
      "tour": "PGA TOUR",
      "course": "Bellerive Country Club",
      "coursePar": 70,
      "location": "St. Louis, MO, USA",
      "startDate": "",
      "endDate": "2026-08-23",
      "roundLabel": "Round 1",
      "status": "Round 1 - In Progress",
      "fieldSize": 50,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "heroStats": {
      "leaderName": "J.J. Spaun",
      "leaderScore": -6,
      "playersUnderPar": 31,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "fieldSize": 50
    },
    "leaderboard": [
      {
        "playerId": "j-j-spaun",
        "playerName": "J.J. Spaun",
        "country": "USA",
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          64
        ],
        "movement": 0
      },
      {
        "playerId": "wyndham-clark",
        "playerName": "Wyndham Clark",
        "country": "USA",
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          64
        ],
        "movement": 0
      },
      {
        "playerId": "rory-mcilroy",
        "playerName": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          64
        ],
        "movement": 0
      },
      {
        "playerId": "gary-woodland",
        "playerName": "Gary Woodland",
        "country": "USA",
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          64
        ],
        "movement": 0
      },
      {
        "playerId": "chris-gotterup",
        "playerName": "Chris Gotterup",
        "country": "USA",
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          55
        ],
        "movement": 0
      },
      {
        "playerId": "ryo-hisatsune",
        "playerName": "Ryo Hisatsune",
        "country": "Japan",
        "position": "6",
        "totalToPar": -5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "alex-fitzpatrick",
        "playerName": "Alex Fitzpatrick",
        "country": "England",
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "ludvig-aberg",
        "playerName": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "michael-thorbjornsen",
        "playerName": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "eric-cole",
        "playerName": "Eric Cole",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "sungjae-im",
        "playerName": "Sungjae Im",
        "country": "South Korea",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "kristoffer-reitan",
        "playerName": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "akshay-bhatia",
        "playerName": "Akshay Bhatia",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "justin-thomas",
        "playerName": "Justin Thomas",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "jacob-bridgeman",
        "playerName": "Jacob Bridgeman",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "roundScores": [
          51
        ],
        "movement": 0
      },
      {
        "playerId": "russell-henley",
        "playerName": "Russell Henley",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "roundScores": [
          51
        ],
        "movement": 0
      },
      {
        "playerId": "patrick-cantlay",
        "playerName": "Patrick Cantlay",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "matt-fitzpatrick",
        "playerName": "Matt Fitzpatrick",
        "country": "England",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "roundScores": [
          55
        ],
        "movement": 0
      },
      {
        "playerId": "jake-knapp",
        "playerName": "Jake Knapp",
        "country": "USA",
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "collin-morikawa",
        "playerName": "Collin Morikawa",
        "country": "USA",
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "aaron-rai",
        "playerName": "Aaron Rai",
        "country": "England",
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "robert-macintyre",
        "playerName": "Robert MacIntyre",
        "country": "Scotland",
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "adam-scott",
        "playerName": "Adam Scott",
        "country": "Australia",
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "ben-griffin",
        "playerName": "Ben Griffin",
        "country": "USA",
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "nico-echavarria",
        "playerName": "Nico Echavarria",
        "country": "Colombia",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "min-woo-lee",
        "playerName": "Min Woo Lee",
        "country": "Australia",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "michael-brennan",
        "playerName": "Michael Brennan",
        "country": "USA",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "tommy-fleetwood",
        "playerName": "Tommy Fleetwood",
        "country": "England",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "roundScores": [
          60
        ],
        "movement": 0
      },
      {
        "playerId": "justin-rose",
        "playerName": "Justin Rose",
        "country": "England",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "alex-smalley",
        "playerName": "Alex Smalley",
        "country": "USA",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "maverick-mcnealy",
        "playerName": "Maverick McNealy",
        "country": "USA",
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "roundScores": [
          49
        ],
        "movement": 0
      },
      {
        "playerId": "xander-schauffele",
        "playerName": "Xander Schauffele",
        "country": "USA",
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "j-t-poston",
        "playerName": "J.T. Poston",
        "country": "USA",
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "ryan-gerard",
        "playerName": "Ryan Gerard",
        "country": "USA",
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "si-woo-kim",
        "playerName": "Si Woo Kim",
        "country": "South Korea",
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "sahith-theegala",
        "playerName": "Sahith Theegala",
        "country": "USA",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "rickie-fowler",
        "playerName": "Rickie Fowler",
        "country": "USA",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "alex-noren",
        "playerName": "Alex Noren",
        "country": "Sweden",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "ryan-fox",
        "playerName": "Ryan Fox",
        "country": "New Zealand",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "viktor-hovland",
        "playerName": "Viktor Hovland",
        "country": "Norway",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "cameron-young",
        "playerName": "Cameron Young",
        "country": "USA",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "matt-mccarty",
        "playerName": "Matt McCarty",
        "country": "USA",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "roundScores": [
          55
        ],
        "movement": 0
      },
      {
        "playerId": "sam-burns",
        "playerName": "Sam Burns",
        "country": "USA",
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "kurt-kitayama",
        "playerName": "Kurt Kitayama",
        "country": "USA",
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "tom-kim",
        "playerName": "Tom Kim",
        "country": "South Korea",
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "hideki-matsuyama",
        "playerName": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "scottie-scheffler",
        "playerName": "Scottie Scheffler",
        "country": "USA",
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "roundScores": [
          60
        ],
        "movement": 0
      },
      {
        "playerId": "nicolai-h-jgaard",
        "playerName": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "bud-cauley",
        "playerName": "Bud Cauley",
        "country": "USA",
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "sepp-straka",
        "playerName": "Sepp Straka",
        "country": "Austria",
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "roundScores": [
          73
        ],
        "movement": 0
      }
    ],
    "players": [
      {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA",
        "position": "T32"
      },
      {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA",
        "position": "T44"
      },
      {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA",
        "position": "T32"
      },
      {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA",
        "position": "T20"
      },
      {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England",
        "position": "T20"
      },
      {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA",
        "position": "T36"
      },
      {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T48"
      },
      {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland",
        "position": "T20"
      },
      {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea",
        "position": "T10"
      },
      {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "T1"
      },
      {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA",
        "position": "T36"
      },
      {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden",
        "position": "T36"
      },
      {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia",
        "position": "T20"
      },
      {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand",
        "position": "T36"
      },
      {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T10"
      },
      {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England",
        "position": "T7"
      },
      {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway",
        "position": "T36"
      },
      {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T7"
      },
      {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA",
        "position": "T20"
      },
      {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia",
        "position": "T25"
      },
      {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia",
        "position": "T25"
      },
      {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T7"
      },
      {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA",
        "position": "T36"
      },
      {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea",
        "position": "T44"
      },
      {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan",
        "position": "6"
      },
      {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA",
        "position": "T36"
      },
      {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA",
        "position": "T25"
      },
      {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA",
        "position": "T32"
      },
      {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA",
        "position": "T48"
      },
      {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England",
        "position": "T25"
      },
      {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England",
        "position": "T25"
      },
      {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T44"
      },
      {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea",
        "position": "T32"
      },
      {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria",
        "position": "T48"
      },
      {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England",
        "position": "T10"
      },
      {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA",
        "position": "T44"
      },
      {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA",
        "position": "T25"
      },
      {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA",
        "position": "T25"
      },
      {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA",
        "position": "T10"
      },
      {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA",
        "position": "T36"
      }
    ]
  },
  "playerSnapshots": {
    "xander-schauffele": {
      "player": {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "j-j-spaun": {
      "player": {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:42 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 64,
          "relativeToPar": -6
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "kurt-kitayama": {
      "player": {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "1:53 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "j-t-poston": {
      "player": {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "1:53 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "eric-cole": {
      "player": {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:18 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "collin-morikawa": {
      "player": {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:47 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "aaron-rai": {
      "player": {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "sahith-theegala": {
      "player": {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:03 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "wyndham-clark": {
      "player": {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:49 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 64,
          "relativeToPar": -6
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "nicolai-h-jgaard": {
      "player": {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:31 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "robert-macintyre": {
      "player": {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland"
      },
      "tournamentStatus": {
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:09 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "sungjae-im": {
      "player": {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:14 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "rory-mcilroy": {
      "player": {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 64,
          "relativeToPar": -6
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "gary-woodland": {
      "player": {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:36 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 64,
          "relativeToPar": -6
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "rickie-fowler": {
      "player": {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:09 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "alex-noren": {
      "player": {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:51 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "adam-scott": {
      "player": {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:36 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "ryan-fox": {
      "player": {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "kristoffer-reitan": {
      "player": {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:27 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "alex-fitzpatrick": {
      "player": {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:27 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "viktor-hovland": {
      "player": {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:42 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "ludvig-aberg": {
      "player": {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:47 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "ben-griffin": {
      "player": {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T20",
        "totalToPar": -2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "nico-echavarria": {
      "player": {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:40 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "min-woo-lee": {
      "player": {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:11 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "akshay-bhatia": {
      "player": {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:38 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "michael-thorbjornsen": {
      "player": {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T7",
        "totalToPar": -4,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:40 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "cameron-young": {
      "player": {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:07 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "tom-kim": {
      "player": {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "chris-gotterup": {
      "player": {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -6,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:22 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 55,
          "relativeToPar": -15
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "justin-thomas": {
      "player": {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:03 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "ryo-hisatsune": {
      "player": {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "6",
        "totalToPar": -5,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:29 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "matt-mccarty": {
      "player": {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 55,
          "relativeToPar": -15
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "michael-brennan": {
      "player": {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:18 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "jacob-bridgeman": {
      "player": {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:44 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 51,
          "relativeToPar": -19
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "ryan-gerard": {
      "player": {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "17",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:11 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "bud-cauley": {
      "player": {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "1:31 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "russell-henley": {
      "player": {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "14",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:44 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 51,
          "relativeToPar": -19
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "tommy-fleetwood": {
      "player": {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "16",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:22 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 60,
          "relativeToPar": -10
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "justin-rose": {
      "player": {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:16 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "hideki-matsuyama": {
      "player": {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:38 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "patrick-cantlay": {
      "player": {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:29 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "si-woo-kim": {
      "player": {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T32",
        "totalToPar": 0,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:07 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "sepp-straka": {
      "player": {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria"
      },
      "tournamentStatus": {
        "position": "T48",
        "totalToPar": 3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "10:14 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "matt-fitzpatrick": {
      "player": {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:33 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 55,
          "relativeToPar": -15
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "scottie-scheffler": {
      "player": {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T44",
        "totalToPar": 2,
        "today": 0,
        "thru": "15",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:33 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 60,
          "relativeToPar": -10
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "alex-smalley": {
      "player": {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:16 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "maverick-mcnealy": {
      "player": {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T25",
        "totalToPar": -1,
        "today": 0,
        "thru": "13",
        "status": "In Progress",
        "movement": 0,
        "nextTeeTime": "2:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 49,
          "relativeToPar": -21
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "jake-knapp": {
      "player": {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T10",
        "totalToPar": -3,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "12:51 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    },
    "sam-burns": {
      "player": {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T36",
        "totalToPar": 1,
        "today": 0,
        "thru": "F",
        "status": "Finish",
        "movement": 0,
        "nextTeeTime": "11:49 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-20T21:56:59.763Z"
    }
  }
};
