import type { GolfSnapshot } from "@/types/golf";

// Auto-generated by scripts/buildGolfSnapshot.ts on 2026-08-13T22:22:06.874Z
export const golfSnapshot: GolfSnapshot = {
  "summary": {
    "tournament": {
      "id": "wgc-bridgestone-invitational-2026",
      "name": "WGC-Bridgestone Invitational",
      "tour": "PGA TOUR",
      "course": "TPC Southwind",
      "coursePar": 70,
      "location": "Memphis, TN, USA",
      "startDate": "",
      "endDate": "2026-08-16",
      "roundLabel": "Round 1",
      "status": "Round 1 - Play Complete",
      "fieldSize": 69,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "heroStats": {
      "leaderName": "Kurt Kitayama",
      "leaderScore": -5,
      "playersUnderPar": 36,
      "cutLine": 0,
      "cutState": "made",
      "cutCount": 0,
      "fieldSize": 69
    },
    "leaderboard": [
      {
        "playerId": "kurt-kitayama",
        "playerName": "Kurt Kitayama",
        "country": "USA",
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "michael-thorbjornsen",
        "playerName": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "jordan-spieth",
        "playerName": "Jordan Spieth",
        "country": "USA",
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "michael-kim",
        "playerName": "Michael Kim",
        "country": "USA",
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "jake-knapp",
        "playerName": "Jake Knapp",
        "country": "USA",
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          65
        ],
        "movement": 0
      },
      {
        "playerId": "sungjae-im",
        "playerName": "Sungjae Im",
        "country": "South Korea",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "gary-woodland",
        "playerName": "Gary Woodland",
        "country": "USA",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "adam-scott",
        "playerName": "Adam Scott",
        "country": "Australia",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "chris-gotterup",
        "playerName": "Chris Gotterup",
        "country": "USA",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "bud-cauley",
        "playerName": "Bud Cauley",
        "country": "USA",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "tommy-fleetwood",
        "playerName": "Tommy Fleetwood",
        "country": "England",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "hideki-matsuyama",
        "playerName": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          66
        ],
        "movement": 0
      },
      {
        "playerId": "xander-schauffele",
        "playerName": "Xander Schauffele",
        "country": "USA",
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "min-woo-lee",
        "playerName": "Min Woo Lee",
        "country": "Australia",
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "patrick-rodgers",
        "playerName": "Patrick Rodgers",
        "country": "USA",
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "sam-burns",
        "playerName": "Sam Burns",
        "country": "USA",
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          67
        ],
        "movement": 0
      },
      {
        "playerId": "rickie-fowler",
        "playerName": "Rickie Fowler",
        "country": "USA",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "viktor-hovland",
        "playerName": "Viktor Hovland",
        "country": "Norway",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "ludvig-aberg",
        "playerName": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "nico-echavarria",
        "playerName": "Nico Echavarria",
        "country": "Colombia",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "harris-english",
        "playerName": "Harris English",
        "country": "USA",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "sepp-straka",
        "playerName": "Sepp Straka",
        "country": "Austria",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "scottie-scheffler",
        "playerName": "Scottie Scheffler",
        "country": "USA",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "alex-smalley",
        "playerName": "Alex Smalley",
        "country": "USA",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "maverick-mcnealy",
        "playerName": "Maverick McNealy",
        "country": "USA",
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          68
        ],
        "movement": 0
      },
      {
        "playerId": "sahith-theegala",
        "playerName": "Sahith Theegala",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "wyndham-clark",
        "playerName": "Wyndham Clark",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "nick-taylor",
        "playerName": "Nick Taylor",
        "country": "Canada",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "cameron-young",
        "playerName": "Cameron Young",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "sam-stevens",
        "playerName": "Sam Stevens",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "shane-lowry",
        "playerName": "Shane Lowry",
        "country": "Ireland",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "tom-kim",
        "playerName": "Tom Kim",
        "country": "South Korea",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "ryo-hisatsune",
        "playerName": "Ryo Hisatsune",
        "country": "Japan",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "jacob-bridgeman",
        "playerName": "Jacob Bridgeman",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "patrick-cantlay",
        "playerName": "Patrick Cantlay",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "keith-mitchell",
        "playerName": "Keith Mitchell",
        "country": "USA",
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          69
        ],
        "movement": 0
      },
      {
        "playerId": "brian-harman",
        "playerName": "Brian Harman",
        "country": "USA",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "justin-thomas",
        "playerName": "Justin Thomas",
        "country": "USA",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "ryan-gerard",
        "playerName": "Ryan Gerard",
        "country": "USA",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "sudarshan-yellamaraju",
        "playerName": "Sudarshan Yellamaraju",
        "country": "Canada",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "si-woo-kim",
        "playerName": "Si Woo Kim",
        "country": "South Korea",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "matt-fitzpatrick",
        "playerName": "Matt Fitzpatrick",
        "country": "England",
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          70
        ],
        "movement": 0
      },
      {
        "playerId": "j-j-spaun",
        "playerName": "J.J. Spaun",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "j-t-poston",
        "playerName": "J.T. Poston",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "collin-morikawa",
        "playerName": "Collin Morikawa",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "alex-noren",
        "playerName": "Alex Noren",
        "country": "Sweden",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "alex-fitzpatrick",
        "playerName": "Alex Fitzpatrick",
        "country": "England",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "pierceson-coody",
        "playerName": "Pierceson Coody",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "aldrich-potgieter",
        "playerName": "Aldrich Potgieter",
        "country": "South Africa",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "jackson-koivun",
        "playerName": "Jackson Koivun",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "russell-henley",
        "playerName": "Russell Henley",
        "country": "USA",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "corey-conners",
        "playerName": "Corey Conners",
        "country": "Canada",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "jordan-smith",
        "playerName": "Jordan Smith",
        "country": "England",
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          71
        ],
        "movement": 0
      },
      {
        "playerId": "eric-cole",
        "playerName": "Eric Cole",
        "country": "USA",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "aaron-rai",
        "playerName": "Aaron Rai",
        "country": "England",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "kristoffer-reitan",
        "playerName": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "akshay-bhatia",
        "playerName": "Akshay Bhatia",
        "country": "USA",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "harry-hall",
        "playerName": "Harry Hall",
        "country": "England",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "ricky-castillo",
        "playerName": "Ricky Castillo",
        "country": "USA",
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          72
        ],
        "movement": 0
      },
      {
        "playerId": "nicolai-h-jgaard",
        "playerName": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "ryan-fox",
        "playerName": "Ryan Fox",
        "country": "New Zealand",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "ben-griffin",
        "playerName": "Ben Griffin",
        "country": "USA",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "matti-schmid",
        "playerName": "Matti Schmid",
        "country": "Germany",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "matt-mccarty",
        "playerName": "Matt McCarty",
        "country": "USA",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "michael-brennan",
        "playerName": "Michael Brennan",
        "country": "USA",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "justin-rose",
        "playerName": "Justin Rose",
        "country": "England",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "max-homa",
        "playerName": "Max Homa",
        "country": "USA",
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          73
        ],
        "movement": 0
      },
      {
        "playerId": "rory-mcilroy",
        "playerName": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "68",
        "totalToPar": 4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          74
        ],
        "movement": 0
      },
      {
        "playerId": "robert-macintyre",
        "playerName": "Robert MacIntyre",
        "country": "Scotland",
        "position": "69",
        "totalToPar": 12,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "roundScores": [
          82
        ],
        "movement": 0
      }
    ],
    "players": [
      {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA",
        "position": "T54"
      },
      {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England",
        "position": "T54"
      },
      {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark",
        "position": "T60"
      },
      {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland",
        "position": "69"
      },
      {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea",
        "position": "T6"
      },
      {
        "id": "brian-harman",
        "name": "Brian Harman",
        "country": "USA",
        "position": "T37"
      },
      {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland",
        "position": "68"
      },
      {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA",
        "position": "T6"
      },
      {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA",
        "position": "T17"
      },
      {
        "id": "nick-taylor",
        "name": "Nick Taylor",
        "country": "Canada",
        "position": "T26"
      },
      {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden",
        "position": "T43"
      },
      {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia",
        "position": "T6"
      },
      {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand",
        "position": "T60"
      },
      {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway",
        "position": "T54"
      },
      {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England",
        "position": "T43"
      },
      {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway",
        "position": "T17"
      },
      {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden",
        "position": "T17"
      },
      {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA",
        "position": "T60"
      },
      {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia",
        "position": "T17"
      },
      {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia",
        "position": "T13"
      },
      {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA",
        "position": "T54"
      },
      {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "sam-stevens",
        "name": "Sam Stevens",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "matti-schmid",
        "name": "Matti Schmid",
        "country": "Germany",
        "position": "T60"
      },
      {
        "id": "shane-lowry",
        "name": "Shane Lowry",
        "country": "Ireland",
        "position": "T26"
      },
      {
        "id": "harry-hall",
        "name": "Harry Hall",
        "country": "England",
        "position": "T54"
      },
      {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea",
        "position": "T26"
      },
      {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA",
        "position": "T6"
      },
      {
        "id": "ricky-castillo",
        "name": "Ricky Castillo",
        "country": "USA",
        "position": "T54"
      },
      {
        "id": "pierceson-coody",
        "name": "Pierceson Coody",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA",
        "position": "T37"
      },
      {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan",
        "position": "T26"
      },
      {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA",
        "position": "T60"
      },
      {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA",
        "position": "T60"
      },
      {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA",
        "position": "T37"
      },
      {
        "id": "aldrich-potgieter",
        "name": "Aldrich Potgieter",
        "country": "South Africa",
        "position": "T43"
      },
      {
        "id": "sudarshan-yellamaraju",
        "name": "Sudarshan Yellamaraju",
        "country": "Canada",
        "position": "T37"
      },
      {
        "id": "jackson-koivun",
        "name": "Jackson Koivun",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA",
        "position": "T6"
      },
      {
        "id": "harris-english",
        "name": "Harris English",
        "country": "USA",
        "position": "T17"
      },
      {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA",
        "position": "T43"
      },
      {
        "id": "jordan-spieth",
        "name": "Jordan Spieth",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England",
        "position": "T6"
      },
      {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England",
        "position": "T60"
      },
      {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan",
        "position": "T6"
      },
      {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "patrick-rodgers",
        "name": "Patrick Rodgers",
        "country": "USA",
        "position": "T13"
      },
      {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea",
        "position": "T37"
      },
      {
        "id": "keith-mitchell",
        "name": "Keith Mitchell",
        "country": "USA",
        "position": "T26"
      },
      {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria",
        "position": "T17"
      },
      {
        "id": "max-homa",
        "name": "Max Homa",
        "country": "USA",
        "position": "T60"
      },
      {
        "id": "michael-kim",
        "name": "Michael Kim",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England",
        "position": "T37"
      },
      {
        "id": "corey-conners",
        "name": "Corey Conners",
        "country": "Canada",
        "position": "T43"
      },
      {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA",
        "position": "T17"
      },
      {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA",
        "position": "T17"
      },
      {
        "id": "jordan-smith",
        "name": "Jordan Smith",
        "country": "England",
        "position": "T43"
      },
      {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA",
        "position": "T17"
      },
      {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA",
        "position": "T1"
      },
      {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA",
        "position": "T13"
      }
    ]
  },
  "playerSnapshots": {
    "xander-schauffele": {
      "player": {
        "id": "xander-schauffele",
        "name": "Xander Schauffele",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "j-j-spaun": {
      "player": {
        "id": "j-j-spaun",
        "name": "J.J. Spaun",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "kurt-kitayama": {
      "player": {
        "id": "kurt-kitayama",
        "name": "Kurt Kitayama",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:15 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "j-t-poston": {
      "player": {
        "id": "j-t-poston",
        "name": "J.T. Poston",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "eric-cole": {
      "player": {
        "id": "eric-cole",
        "name": "Eric Cole",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "collin-morikawa": {
      "player": {
        "id": "collin-morikawa",
        "name": "Collin Morikawa",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "aaron-rai": {
      "player": {
        "id": "aaron-rai",
        "name": "Aaron Rai",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sahith-theegala": {
      "player": {
        "id": "sahith-theegala",
        "name": "Sahith Theegala",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "wyndham-clark": {
      "player": {
        "id": "wyndham-clark",
        "name": "Wyndham Clark",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "nicolai-h-jgaard": {
      "player": {
        "id": "nicolai-h-jgaard",
        "name": "Nicolai Højgaard",
        "country": "Denmark"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:15 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "robert-macintyre": {
      "player": {
        "id": "robert-macintyre",
        "name": "Robert MacIntyre",
        "country": "Scotland"
      },
      "tournamentStatus": {
        "position": "69",
        "totalToPar": 12,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 82,
          "relativeToPar": 12
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sungjae-im": {
      "player": {
        "id": "sungjae-im",
        "name": "Sungjae Im",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "brian-harman": {
      "player": {
        "id": "brian-harman",
        "name": "Brian Harman",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "rory-mcilroy": {
      "player": {
        "id": "rory-mcilroy",
        "name": "Rory McIlroy",
        "country": "Northern Ireland"
      },
      "tournamentStatus": {
        "position": "68",
        "totalToPar": 4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:30 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 74,
          "relativeToPar": 4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "gary-woodland": {
      "player": {
        "id": "gary-woodland",
        "name": "Gary Woodland",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:40 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "rickie-fowler": {
      "player": {
        "id": "rickie-fowler",
        "name": "Rickie Fowler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:25 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "nick-taylor": {
      "player": {
        "id": "nick-taylor",
        "name": "Nick Taylor",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "alex-noren": {
      "player": {
        "id": "alex-noren",
        "name": "Alex Noren",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "adam-scott": {
      "player": {
        "id": "adam-scott",
        "name": "Adam Scott",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:15 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ryan-fox": {
      "player": {
        "id": "ryan-fox",
        "name": "Ryan Fox",
        "country": "New Zealand"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:15 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "kristoffer-reitan": {
      "player": {
        "id": "kristoffer-reitan",
        "name": "Kristoffer Reitan",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "alex-fitzpatrick": {
      "player": {
        "id": "alex-fitzpatrick",
        "name": "Alex Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "viktor-hovland": {
      "player": {
        "id": "viktor-hovland",
        "name": "Viktor Hovland",
        "country": "Norway"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ludvig-aberg": {
      "player": {
        "id": "ludvig-aberg",
        "name": "Ludvig Åberg",
        "country": "Sweden"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ben-griffin": {
      "player": {
        "id": "ben-griffin",
        "name": "Ben Griffin",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "nico-echavarria": {
      "player": {
        "id": "nico-echavarria",
        "name": "Nico Echavarria",
        "country": "Colombia"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "min-woo-lee": {
      "player": {
        "id": "min-woo-lee",
        "name": "Min Woo Lee",
        "country": "Australia"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "akshay-bhatia": {
      "player": {
        "id": "akshay-bhatia",
        "name": "Akshay Bhatia",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "michael-thorbjornsen": {
      "player": {
        "id": "michael-thorbjornsen",
        "name": "Michael Thorbjornsen",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:00 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "cameron-young": {
      "player": {
        "id": "cameron-young",
        "name": "Cameron Young",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:35 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sam-stevens": {
      "player": {
        "id": "sam-stevens",
        "name": "Sam Stevens",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "matti-schmid": {
      "player": {
        "id": "matti-schmid",
        "name": "Matti Schmid",
        "country": "Germany"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "2:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "shane-lowry": {
      "player": {
        "id": "shane-lowry",
        "name": "Shane Lowry",
        "country": "Ireland"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "harry-hall": {
      "player": {
        "id": "harry-hall",
        "name": "Harry Hall",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "tom-kim": {
      "player": {
        "id": "tom-kim",
        "name": "Tom Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:20 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "chris-gotterup": {
      "player": {
        "id": "chris-gotterup",
        "name": "Chris Gotterup",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ricky-castillo": {
      "player": {
        "id": "ricky-castillo",
        "name": "Ricky Castillo",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T54",
        "totalToPar": 2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "2:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 72,
          "relativeToPar": 2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "pierceson-coody": {
      "player": {
        "id": "pierceson-coody",
        "name": "Pierceson Coody",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "justin-thomas": {
      "player": {
        "id": "justin-thomas",
        "name": "Justin Thomas",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:35 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ryo-hisatsune": {
      "player": {
        "id": "ryo-hisatsune",
        "name": "Ryo Hisatsune",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "matt-mccarty": {
      "player": {
        "id": "matt-mccarty",
        "name": "Matt McCarty",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "michael-brennan": {
      "player": {
        "id": "michael-brennan",
        "name": "Michael Brennan",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "jacob-bridgeman": {
      "player": {
        "id": "jacob-bridgeman",
        "name": "Jacob Bridgeman",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "ryan-gerard": {
      "player": {
        "id": "ryan-gerard",
        "name": "Ryan Gerard",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:05 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "aldrich-potgieter": {
      "player": {
        "id": "aldrich-potgieter",
        "name": "Aldrich Potgieter",
        "country": "South Africa"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sudarshan-yellamaraju": {
      "player": {
        "id": "sudarshan-yellamaraju",
        "name": "Sudarshan Yellamaraju",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "jackson-koivun": {
      "player": {
        "id": "jackson-koivun",
        "name": "Jackson Koivun",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "bud-cauley": {
      "player": {
        "id": "bud-cauley",
        "name": "Bud Cauley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:05 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "harris-english": {
      "player": {
        "id": "harris-english",
        "name": "Harris English",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "russell-henley": {
      "player": {
        "id": "russell-henley",
        "name": "Russell Henley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:25 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "jordan-spieth": {
      "player": {
        "id": "jordan-spieth",
        "name": "Jordan Spieth",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:10 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "tommy-fleetwood": {
      "player": {
        "id": "tommy-fleetwood",
        "name": "Tommy Fleetwood",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:10 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "justin-rose": {
      "player": {
        "id": "justin-rose",
        "name": "Justin Rose",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "hideki-matsuyama": {
      "player": {
        "id": "hideki-matsuyama",
        "name": "Hideki Matsuyama",
        "country": "Japan"
      },
      "tournamentStatus": {
        "position": "T6",
        "totalToPar": -4,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:45 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 66,
          "relativeToPar": -4
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "patrick-cantlay": {
      "player": {
        "id": "patrick-cantlay",
        "name": "Patrick Cantlay",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:50 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "patrick-rodgers": {
      "player": {
        "id": "patrick-rodgers",
        "name": "Patrick Rodgers",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:55 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "si-woo-kim": {
      "player": {
        "id": "si-woo-kim",
        "name": "Si Woo Kim",
        "country": "South Korea"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:35 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "keith-mitchell": {
      "player": {
        "id": "keith-mitchell",
        "name": "Keith Mitchell",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T26",
        "totalToPar": -1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:40 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 69,
          "relativeToPar": -1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sepp-straka": {
      "player": {
        "id": "sepp-straka",
        "name": "Sepp Straka",
        "country": "Austria"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:00 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "max-homa": {
      "player": {
        "id": "max-homa",
        "name": "Max Homa",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T60",
        "totalToPar": 3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:20 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 73,
          "relativeToPar": 3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "michael-kim": {
      "player": {
        "id": "michael-kim",
        "name": "Michael Kim",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:45 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "matt-fitzpatrick": {
      "player": {
        "id": "matt-fitzpatrick",
        "name": "Matt Fitzpatrick",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T37",
        "totalToPar": 0,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 70,
          "relativeToPar": 0
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "corey-conners": {
      "player": {
        "id": "corey-conners",
        "name": "Corey Conners",
        "country": "Canada"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "8:10 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "scottie-scheffler": {
      "player": {
        "id": "scottie-scheffler",
        "name": "Scottie Scheffler",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:30 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "alex-smalley": {
      "player": {
        "id": "alex-smalley",
        "name": "Alex Smalley",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "12:40 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "jordan-smith": {
      "player": {
        "id": "jordan-smith",
        "name": "Jordan Smith",
        "country": "England"
      },
      "tournamentStatus": {
        "position": "T43",
        "totalToPar": 1,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "1:55 PM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 71,
          "relativeToPar": 1
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "maverick-mcnealy": {
      "player": {
        "id": "maverick-mcnealy",
        "name": "Maverick McNealy",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T17",
        "totalToPar": -2,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "11:30 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 68,
          "relativeToPar": -2
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "jake-knapp": {
      "player": {
        "id": "jake-knapp",
        "name": "Jake Knapp",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T1",
        "totalToPar": -5,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "9:00 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 65,
          "relativeToPar": -5
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    },
    "sam-burns": {
      "player": {
        "id": "sam-burns",
        "name": "Sam Burns",
        "country": "USA"
      },
      "tournamentStatus": {
        "position": "T13",
        "totalToPar": -3,
        "today": 0,
        "thru": "—",
        "status": "Scheduled",
        "movement": 0,
        "nextTeeTime": "10:25 AM EDT"
      },
      "roundByRound": [
        {
          "round": 1,
          "score": 67,
          "relativeToPar": -3
        }
      ],
      "scoring": {
        "birdies": 0,
        "bogeys": 0,
        "eagles": 0,
        "doubleBogeys": 0,
        "pars": 0
      },
      "generatedAt": "2026-08-13T22:22:06.874Z"
    }
  }
};
