import type { NbaSnapshot } from "@/types/nba";

// Auto-generated by scripts/updateNbaSnapshot.ts. Run `npm run update:nba`
// to refresh standings, leaderboards, and per-team schedules from ESPN.
// This seed value is intentionally empty so the route renders without
// network access; replace with the script output before deploying.
export const nbaSnapshot: NbaSnapshot = {
  season: "2025/26",
  updatedAt: new Date().toISOString().slice(0, 10),
  sourceLabel: "ESPN",
  sourceUrls: {
    standings: "https://www.espn.com/nba/standings",
    leaders: "https://www.espn.com/nba/statistics",
    scoreboard: "https://www.espn.com/nba/scoreboard"
  },
  teamsByConference: { east: [], west: [] },
  scorers: [],
  rebounders: [],
  assistLeaders: [],
  recentFixtures: [],
  upcomingFixtures: [],
  teams: [],
  teamSnapshots: {}
};
