import type { ScorePoolsSnapshot } from "@/types/scorePools";

// Auto-generated by scripts/buildScorePoolsSnapshot.ts on 2026-07-20T06:27:09.599Z
export const scorePoolsSnapshot: ScorePoolsSnapshot = {
  "generatedAt": "2026-07-20T06:27:09.599Z",
  "leagues": [
    {
      "key": "premier-league",
      "name": "Premier League",
      "sport": "soccer",
      "season": "2026-27",
      "sources": {
        "fixtures": "manual entry",
        "odds": "manual entry"
      },
      "generatedAt": "2026-07-20T06:27:09.599Z",
      "sample": false,
      "notes": [
        "API_FOOTBALL_KEY is not set, so fixtures come from manual/CSV entries only.",
        "THE_ODDS_API_KEY is not set, so odds come from manual/CSV entries only."
      ],
      "fixtures": [],
      "standings": []
    },
    {
      "key": "sample-cup",
      "name": "Sample Cup",
      "sport": "soccer",
      "season": "2026 demo",
      "sources": {
        "fixtures": "manual entry",
        "odds": "manual entry"
      },
      "generatedAt": "2026-07-20T06:27:09.599Z",
      "sample": true,
      "notes": [
        "Sample data for trying the tool. Teams and odds are fictional; configure a live league in scripts/data/scorePoolsConfig.ts or drop CSV odds in scripts/data/score-pools/ to replace it."
      ],
      "fixtures": [
        {
          "id": "sc-r1-4",
          "kickoff": "2026-07-14T19:00:00.000Z",
          "homeTeam": "Westmoor",
          "awayTeam": "Pinewood",
          "stage": "Round 1",
          "round": null,
          "knockout": true,
          "status": "finished",
          "result": {
            "ninetyMinutes": {
              "home": 1,
              "away": 1
            },
            "afterExtraTime": {
              "home": 1,
              "away": 1
            },
            "penaltyWinner": "home"
          },
          "lineupsConfirmed": null,
          "injuryNotes": [],
          "odds": [
            {
              "fetchedAt": "2026-07-14T09:00:00.000Z",
              "bookmaker": null,
              "manual": true,
              "moneyline": {
                "home": 2.45,
                "draw": 3.1,
                "away": 3.15
              },
              "totals": {
                "line": 2.5,
                "over": 2.15,
                "under": 1.75
              }
            }
          ]
        },
        {
          "id": "sc-qf-1",
          "kickoff": "2026-08-04T19:00:00.000Z",
          "homeTeam": "Harbor City",
          "awayTeam": "Ironvale",
          "stage": "Quarterfinal",
          "round": null,
          "knockout": true,
          "status": "scheduled",
          "result": null,
          "lineupsConfirmed": null,
          "injuryNotes": [],
          "odds": [
            {
              "fetchedAt": "2026-07-19T08:00:00.000Z",
              "bookmaker": null,
              "manual": true,
              "moneyline": {
                "home": 2.55,
                "draw": 3.05,
                "away": 3
              },
              "totals": {
                "line": 2.5,
                "over": 2.1,
                "under": 1.78
              }
            }
          ]
        },
        {
          "id": "sc-qf-2",
          "kickoff": "2026-08-05T16:30:00.000Z",
          "homeTeam": "Meridian",
          "awayTeam": "Northgate",
          "stage": "Quarterfinal",
          "round": null,
          "knockout": true,
          "status": "scheduled",
          "result": null,
          "lineupsConfirmed": null,
          "injuryNotes": [],
          "odds": [
            {
              "fetchedAt": "2026-07-19T08:00:00.000Z",
              "bookmaker": null,
              "manual": true,
              "moneyline": {
                "home": 1.36,
                "draw": 5,
                "away": 8.5
              },
              "totals": {
                "line": 2.5,
                "over": 1.62,
                "under": 2.3
              }
            }
          ]
        },
        {
          "id": "sc-group-1",
          "kickoff": "2026-08-06T19:00:00.000Z",
          "homeTeam": "Eastport",
          "awayTeam": "Silver Coast",
          "stage": "Group A, final matchday",
          "round": null,
          "knockout": false,
          "status": "scheduled",
          "result": null,
          "lineupsConfirmed": null,
          "injuryNotes": [],
          "odds": [
            {
              "fetchedAt": "2026-07-19T08:00:00.000Z",
              "bookmaker": null,
              "manual": true,
              "moneyline": {
                "home": 2.7,
                "draw": 3.1,
                "away": 2.75
              },
              "totals": {
                "line": 2.5,
                "over": 2,
                "under": 1.85
              }
            }
          ]
        }
      ],
      "standings": [
        {
          "group": "Group A",
          "rows": [
            {
              "team": "Eastport",
              "position": 1,
              "played": 2,
              "points": 6,
              "qualified": true,
              "eliminated": null
            },
            {
              "team": "Silver Coast",
              "position": 2,
              "played": 2,
              "points": 4,
              "qualified": true,
              "eliminated": null
            },
            {
              "team": "Northgate",
              "position": 3,
              "played": 2,
              "points": 1,
              "qualified": null,
              "eliminated": true
            },
            {
              "team": "Pinewood",
              "position": 4,
              "played": 2,
              "points": 0,
              "qualified": null,
              "eliminated": true
            }
          ]
        }
      ]
    }
  ]
};
