import type { TechStartupSnapshot } from "@/types/techStartup";

// Generated by scripts/buildTechStartupSnapshot.ts. Edit the curated seed in that
// script and re-run `npm run update:tech-startups` rather than editing this file.
export const techStartupSnapshot: TechStartupSnapshot = {
  "generatedAt": "2026-06-09T16:39:05.583Z",
  "asOf": "2026-05-01",
  "verified": false,
  "sourceLabel": "Curated from public reporting",
  "sourceUrl": "https://news.crunchbase.com",
  "disclaimer": "Funding totals, valuations, and round details are approximate figures compiled from public reporting and press releases, current as of the as-of date shown. They are editorial estimates for illustration and research, not verified financials or investment advice.",
  "currency": "USD",
  "startups": [
    {
      "id": "openai",
      "name": "OpenAI",
      "description": "Frontier AI lab behind ChatGPT and the GPT model family, spanning consumer assistants and enterprise APIs.",
      "sector": "sector-ai",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2015,
      "website": "https://openai.com",
      "totalRaised": 64000000000,
      "valuation": 300000000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Late-stage round",
        "amount": 40000000000,
        "date": "2025-03",
        "leadInvestors": [
          "SoftBank"
        ]
      },
      "notableInvestors": [
        "Microsoft",
        "SoftBank",
        "Thrive Capital"
      ],
      "tags": [
        "foundation models",
        "ChatGPT",
        "generative AI"
      ],
      "momentumScore": 74
    },
    {
      "id": "anthropic",
      "name": "Anthropic",
      "description": "AI safety company building the Claude family of models for assistants, coding, and enterprise workloads.",
      "sector": "sector-ai",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2021,
      "website": "https://www.anthropic.com",
      "totalRaised": 27000000000,
      "valuation": 61500000000,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series E",
        "amount": 3500000000,
        "date": "2025-03",
        "leadInvestors": [
          "Lightspeed Venture Partners"
        ]
      },
      "notableInvestors": [
        "Google",
        "Amazon",
        "Lightspeed",
        "Spark Capital"
      ],
      "tags": [
        "foundation models",
        "Claude",
        "AI safety"
      ],
      "momentumScore": 69.8
    },
    {
      "id": "xai",
      "name": "xAI",
      "description": "Elon Musk's AI venture developing the Grok assistant and training infrastructure integrated with X.",
      "sector": "sector-ai",
      "stage": "stage-late",
      "headquarters": "Palo Alto, CA",
      "country": "United States",
      "founded": 2023,
      "website": "https://x.ai",
      "totalRaised": 12000000000,
      "valuation": 50000000000,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series C",
        "amount": 6000000000,
        "date": "2024-12",
        "leadInvestors": [
          "Valor Equity Partners"
        ]
      },
      "notableInvestors": [
        "Valor Equity Partners",
        "Sequoia Capital",
        "Andreessen Horowitz"
      ],
      "tags": [
        "foundation models",
        "Grok",
        "compute"
      ],
      "momentumScore": 62.9
    },
    {
      "id": "mistral-ai",
      "name": "Mistral AI",
      "description": "European AI lab shipping open-weight and commercial models with a focus on efficiency and sovereignty.",
      "sector": "sector-ai",
      "stage": "stage-growth",
      "headquarters": "Paris",
      "country": "France",
      "founded": 2023,
      "website": "https://mistral.ai",
      "totalRaised": 1100000000,
      "valuation": 6200000000,
      "employees": "51-200",
      "lastRound": {
        "stage": "Series B",
        "amount": 640000000,
        "date": "2024-06",
        "leadInvestors": [
          "General Catalyst"
        ]
      },
      "notableInvestors": [
        "General Catalyst",
        "Andreessen Horowitz",
        "Lightspeed"
      ],
      "tags": [
        "open-weight models",
        "European AI"
      ],
      "momentumScore": 43.6
    },
    {
      "id": "perplexity",
      "name": "Perplexity AI",
      "description": "Conversational answer engine that pairs live web retrieval with large language models for cited responses.",
      "sector": "sector-ai",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2022,
      "website": "https://www.perplexity.ai",
      "totalRaised": 1000000000,
      "valuation": 9000000000,
      "employees": "201-500",
      "lastRound": {
        "stage": "Growth round",
        "amount": 500000000,
        "date": "2024-12",
        "leadInvestors": [
          "Institutional Venture Partners"
        ]
      },
      "notableInvestors": [
        "IVP",
        "NEA",
        "Nvidia",
        "Jeff Bezos"
      ],
      "tags": [
        "answer engine",
        "search",
        "RAG"
      ],
      "momentumScore": 58.5
    },
    {
      "id": "scale-ai",
      "name": "Scale AI",
      "description": "Data engine for AI — labeling, evaluation, and model-readiness infrastructure for enterprises and governments.",
      "sector": "sector-ai",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2016,
      "website": "https://scale.com",
      "totalRaised": 1600000000,
      "valuation": 13800000000,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series F",
        "amount": 1000000000,
        "date": "2024-05",
        "leadInvestors": [
          "Accel"
        ]
      },
      "notableInvestors": [
        "Accel",
        "Index Ventures",
        "Founders Fund"
      ],
      "tags": [
        "data labeling",
        "model evaluation"
      ],
      "momentumScore": 42.2
    },
    {
      "id": "cohere",
      "name": "Cohere",
      "description": "Enterprise-focused LLM provider offering retrieval-augmented generation and private deployment options.",
      "sector": "sector-ai",
      "stage": "stage-growth",
      "headquarters": "Toronto",
      "country": "Canada",
      "founded": 2019,
      "website": "https://cohere.com",
      "totalRaised": 970000000,
      "valuation": 5500000000,
      "employees": "201-500",
      "lastRound": {
        "stage": "Series D",
        "amount": 500000000,
        "date": "2024-07",
        "leadInvestors": [
          "PSP Investments"
        ]
      },
      "notableInvestors": [
        "Inovia Capital",
        "Nvidia",
        "Oracle"
      ],
      "tags": [
        "enterprise LLMs",
        "RAG"
      ],
      "momentumScore": 45.7
    },
    {
      "id": "hugging-face",
      "name": "Hugging Face",
      "description": "Open-source machine-learning hub hosting models, datasets, and tooling used across the AI community.",
      "sector": "sector-ai",
      "stage": "stage-growth",
      "headquarters": "New York, NY",
      "country": "United States",
      "founded": 2016,
      "website": "https://huggingface.co",
      "totalRaised": 395000000,
      "valuation": 4500000000,
      "employees": "201-500",
      "lastRound": {
        "stage": "Series D",
        "amount": 235000000,
        "date": "2023-08",
        "leadInvestors": [
          "Salesforce Ventures"
        ]
      },
      "notableInvestors": [
        "Sequoia",
        "Coatue",
        "Nvidia",
        "Google"
      ],
      "tags": [
        "open-source ML",
        "model hub"
      ],
      "momentumScore": 39.6
    },
    {
      "id": "sierra",
      "name": "Sierra",
      "description": "Conversational AI agent platform for customer experience, founded by Bret Taylor and Clay Bavor.",
      "sector": "sector-ai",
      "stage": "stage-early",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2023,
      "website": "https://sierra.ai",
      "totalRaised": 285000000,
      "valuation": 4500000000,
      "employees": "51-200",
      "lastRound": {
        "stage": "Series B",
        "amount": 175000000,
        "date": "2024-10",
        "leadInvestors": [
          "Greenoaks"
        ]
      },
      "notableInvestors": [
        "Sequoia",
        "Benchmark",
        "Thrive Capital"
      ],
      "tags": [
        "AI agents",
        "customer experience"
      ],
      "momentumScore": 51.7
    },
    {
      "id": "skild-ai",
      "name": "Skild AI",
      "description": "Robotics startup training a general-purpose foundation model for embodied agents across hardware.",
      "sector": "sector-ai",
      "stage": "stage-early",
      "headquarters": "Pittsburgh, PA",
      "country": "United States",
      "founded": 2023,
      "website": "https://www.skild.ai",
      "totalRaised": 300000000,
      "valuation": 1500000000,
      "employees": "11-50",
      "lastRound": {
        "stage": "Series A",
        "amount": 300000000,
        "date": "2024-07",
        "leadInvestors": [
          "Lightspeed Venture Partners"
        ]
      },
      "notableInvestors": [
        "Lightspeed",
        "Coatue",
        "SoftBank"
      ],
      "tags": [
        "robotics",
        "embodied AI"
      ],
      "momentumScore": 44.2
    },
    {
      "id": "stripe",
      "name": "Stripe",
      "description": "Payments and financial infrastructure platform powering online businesses, marketplaces, and platforms.",
      "sector": "sector-fintech",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2010,
      "website": "https://stripe.com",
      "totalRaised": 9400000000,
      "valuation": 70000000000,
      "employees": "5,001-10,000",
      "lastRound": {
        "stage": "Tender offer",
        "amount": 694000000,
        "date": "2025-02",
        "leadInvestors": [
          "Sequoia Capital"
        ]
      },
      "notableInvestors": [
        "Sequoia",
        "Andreessen Horowitz",
        "Thrive Capital"
      ],
      "tags": [
        "payments",
        "financial infrastructure"
      ],
      "momentumScore": 65.3
    },
    {
      "id": "revolut",
      "name": "Revolut",
      "description": "Global neobank offering banking, FX, investing, and crypto across consumer and business accounts.",
      "sector": "sector-fintech",
      "stage": "stage-late",
      "headquarters": "London",
      "country": "United Kingdom",
      "founded": 2015,
      "website": "https://www.revolut.com",
      "totalRaised": 2000000000,
      "valuation": 45000000000,
      "employees": "5,001-10,000",
      "lastRound": {
        "stage": "Secondary",
        "amount": 500000000,
        "date": "2024-08",
        "leadInvestors": [
          "Coatue"
        ]
      },
      "notableInvestors": [
        "SoftBank",
        "Tiger Global",
        "Index Ventures"
      ],
      "tags": [
        "neobank",
        "consumer fintech"
      ],
      "momentumScore": 49.6
    },
    {
      "id": "ramp",
      "name": "Ramp",
      "description": "Corporate card and spend-management platform that automates expenses, bill pay, and procurement.",
      "sector": "sector-fintech",
      "stage": "stage-growth",
      "headquarters": "New York, NY",
      "country": "United States",
      "founded": 2019,
      "website": "https://ramp.com",
      "totalRaised": 2000000000,
      "valuation": 13000000000,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series E",
        "amount": 150000000,
        "date": "2025-04",
        "leadInvestors": [
          "Founders Fund"
        ]
      },
      "notableInvestors": [
        "Founders Fund",
        "Thrive Capital",
        "Sequoia"
      ],
      "tags": [
        "corporate cards",
        "spend management"
      ],
      "momentumScore": 67.2
    },
    {
      "id": "plaid",
      "name": "Plaid",
      "description": "Open-banking data network connecting consumer financial accounts to fintech apps and services.",
      "sector": "sector-fintech",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2013,
      "website": "https://plaid.com",
      "totalRaised": 734000000,
      "valuation": 6100000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Series D",
        "amount": 575000000,
        "date": "2025-04",
        "leadInvestors": [
          "Franklin Templeton"
        ]
      },
      "notableInvestors": [
        "NEA",
        "Andreessen Horowitz",
        "Index Ventures"
      ],
      "tags": [
        "open banking",
        "data connectivity"
      ],
      "momentumScore": 68.5
    },
    {
      "id": "brex",
      "name": "Brex",
      "description": "Financial stack for startups and enterprises combining corporate cards, banking, and expense controls.",
      "sector": "sector-fintech",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2017,
      "website": "https://www.brex.com",
      "totalRaised": 1500000000,
      "valuation": 12300000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Series D-2",
        "amount": 300000000,
        "date": "2022-01",
        "leadInvestors": [
          "Greenoaks"
        ]
      },
      "notableInvestors": [
        "Y Combinator",
        "Ribbit Capital",
        "Greenoaks"
      ],
      "tags": [
        "corporate cards",
        "startup banking"
      ],
      "momentumScore": 40.6
    },
    {
      "id": "databricks",
      "name": "Databricks",
      "description": "Data and AI lakehouse platform unifying analytics, ML, and governance on top of open formats.",
      "sector": "sector-devtools",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2013,
      "website": "https://www.databricks.com",
      "totalRaised": 14000000000,
      "valuation": 62000000000,
      "employees": "5,001-10,000",
      "lastRound": {
        "stage": "Series J",
        "amount": 10000000000,
        "date": "2024-12",
        "leadInvestors": [
          "Thrive Capital"
        ]
      },
      "notableInvestors": [
        "Andreessen Horowitz",
        "Thrive Capital",
        "DST Global"
      ],
      "tags": [
        "data lakehouse",
        "analytics"
      ],
      "momentumScore": 63.7
    },
    {
      "id": "vercel",
      "name": "Vercel",
      "description": "Frontend cloud and deployment platform behind Next.js, focused on developer experience and edge delivery.",
      "sector": "sector-devtools",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2015,
      "website": "https://vercel.com",
      "totalRaised": 563000000,
      "valuation": 3250000000,
      "employees": "201-500",
      "lastRound": {
        "stage": "Series E",
        "amount": 250000000,
        "date": "2024-05",
        "leadInvestors": [
          "Accel"
        ]
      },
      "notableInvestors": [
        "Accel",
        "GV",
        "Bedrock"
      ],
      "tags": [
        "frontend cloud",
        "Next.js"
      ],
      "momentumScore": 39.5
    },
    {
      "id": "anysphere",
      "name": "Anysphere (Cursor)",
      "description": "Maker of the Cursor AI code editor, building agentic developer tooling on top of large language models.",
      "sector": "sector-devtools",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2022,
      "website": "https://www.cursor.com",
      "totalRaised": 1000000000,
      "valuation": 9900000000,
      "employees": "51-200",
      "lastRound": {
        "stage": "Series C",
        "amount": 900000000,
        "date": "2025-05",
        "leadInvestors": [
          "Thrive Capital"
        ]
      },
      "notableInvestors": [
        "Thrive Capital",
        "Andreessen Horowitz",
        "Accel"
      ],
      "tags": [
        "AI code editor",
        "developer tools"
      ],
      "momentumScore": 71.9
    },
    {
      "id": "canva",
      "name": "Canva",
      "description": "Visual design platform spanning documents, presentations, and brand workflows for teams and creators.",
      "sector": "sector-saas",
      "stage": "stage-late",
      "headquarters": "Sydney",
      "country": "Australia",
      "founded": 2013,
      "website": "https://www.canva.com",
      "totalRaised": 580000000,
      "valuation": 32000000000,
      "employees": "5,001-10,000",
      "lastRound": {
        "stage": "Tender offer",
        "amount": 1500000000,
        "date": "2024-08",
        "leadInvestors": [
          "ICONIQ Growth"
        ]
      },
      "notableInvestors": [
        "Sequoia",
        "Blackbird Ventures",
        "Bessemer"
      ],
      "tags": [
        "design platform",
        "creative SaaS"
      ],
      "momentumScore": 50.8
    },
    {
      "id": "rippling",
      "name": "Rippling",
      "description": "Workforce platform unifying HR, IT, and finance — payroll, devices, and spend in one system of record.",
      "sector": "sector-saas",
      "stage": "stage-late",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2016,
      "website": "https://www.rippling.com",
      "totalRaised": 1700000000,
      "valuation": 16800000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Series G",
        "amount": 450000000,
        "date": "2025-05",
        "leadInvestors": [
          "GIC"
        ]
      },
      "notableInvestors": [
        "Kleiner Perkins",
        "Founders Fund",
        "Greenoaks"
      ],
      "tags": [
        "HR & IT platform",
        "workforce management"
      ],
      "momentumScore": 71.3
    },
    {
      "id": "notion",
      "name": "Notion",
      "description": "Connected workspace combining docs, wikis, and project management with embedded AI assistance.",
      "sector": "sector-saas",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2013,
      "website": "https://www.notion.so",
      "totalRaised": 343000000,
      "valuation": 10000000000,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series C",
        "amount": 275000000,
        "date": "2021-10",
        "leadInvestors": [
          "Coatue",
          "Sequoia"
        ]
      },
      "notableInvestors": [
        "Index Ventures",
        "Coatue",
        "Sequoia"
      ],
      "tags": [
        "workspace",
        "productivity"
      ],
      "momentumScore": 40.3
    },
    {
      "id": "deel",
      "name": "Deel",
      "description": "Global payroll and employer-of-record platform handling hiring, compliance, and payments across borders.",
      "sector": "sector-saas",
      "stage": "stage-growth",
      "headquarters": "San Francisco, CA",
      "country": "United States",
      "founded": 2019,
      "website": "https://www.deel.com",
      "totalRaised": 680000000,
      "valuation": 12100000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Series D extension",
        "amount": 300000000,
        "date": "2025-01",
        "leadInvestors": [
          "Andreessen Horowitz"
        ]
      },
      "notableInvestors": [
        "Andreessen Horowitz",
        "Coatue",
        "Spark Capital"
      ],
      "tags": [
        "global payroll",
        "employer of record"
      ],
      "momentumScore": 60.6
    },
    {
      "id": "spacex",
      "name": "SpaceX",
      "description": "Launch and satellite company operating Falcon and Starship vehicles and the Starlink broadband network.",
      "sector": "sector-defense",
      "stage": "stage-late",
      "headquarters": "Hawthorne, CA",
      "country": "United States",
      "founded": 2002,
      "website": "https://www.spacex.com",
      "totalRaised": 10000000000,
      "valuation": 350000000000,
      "employees": "10,001+",
      "lastRound": {
        "stage": "Tender offer",
        "amount": 1250000000,
        "date": "2024-12",
        "leadInvestors": [
          "Existing investors"
        ]
      },
      "notableInvestors": [
        "Founders Fund",
        "Sequoia",
        "Andreessen Horowitz"
      ],
      "tags": [
        "launch",
        "Starlink",
        "space"
      ],
      "momentumScore": 62.1
    },
    {
      "id": "anduril",
      "name": "Anduril Industries",
      "description": "Defense technology company building autonomous systems and the Lattice software platform.",
      "sector": "sector-defense",
      "stage": "stage-late",
      "headquarters": "Costa Mesa, CA",
      "country": "United States",
      "founded": 2017,
      "website": "https://www.anduril.com",
      "totalRaised": 3700000000,
      "valuation": 28000000000,
      "employees": "1,001-5,000",
      "lastRound": {
        "stage": "Series F",
        "amount": 1500000000,
        "date": "2024-08",
        "leadInvestors": [
          "Founders Fund"
        ]
      },
      "notableInvestors": [
        "Founders Fund",
        "Andreessen Horowitz",
        "8VC"
      ],
      "tags": [
        "defense tech",
        "autonomy"
      ],
      "momentumScore": 50.7
    },
    {
      "id": "helsing",
      "name": "Helsing",
      "description": "European defense AI company building software for real-time battlefield awareness and autonomy.",
      "sector": "sector-defense",
      "stage": "stage-growth",
      "headquarters": "Munich",
      "country": "Germany",
      "founded": 2021,
      "website": "https://helsing.ai",
      "totalRaised": 870000000,
      "valuation": 5400000000,
      "employees": "201-500",
      "lastRound": {
        "stage": "Series C",
        "amount": 450000000,
        "date": "2024-07",
        "leadInvestors": [
          "General Catalyst"
        ]
      },
      "notableInvestors": [
        "General Catalyst",
        "Accel",
        "Lightspeed"
      ],
      "tags": [
        "defense AI",
        "European defense"
      ],
      "momentumScore": 45.6
    },
    {
      "id": "commonwealth-fusion",
      "name": "Commonwealth Fusion Systems",
      "description": "MIT spinout building the SPARC tokamak to commercialize fusion energy with high-temperature superconductors.",
      "sector": "sector-climate",
      "stage": "stage-growth",
      "headquarters": "Devens, MA",
      "country": "United States",
      "founded": 2018,
      "website": "https://cfs.energy",
      "totalRaised": 2000000000,
      "valuation": null,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series B",
        "amount": 1800000000,
        "date": "2021-12",
        "leadInvestors": [
          "Tiger Global"
        ]
      },
      "notableInvestors": [
        "Breakthrough Energy Ventures",
        "Bill Gates",
        "Google"
      ],
      "tags": [
        "fusion energy",
        "deep tech"
      ],
      "momentumScore": 41.7
    },
    {
      "id": "helion-energy",
      "name": "Helion Energy",
      "description": "Fusion startup pursuing a pulsed, non-thermal approach to electricity generation with commercial timelines.",
      "sector": "sector-climate",
      "stage": "stage-growth",
      "headquarters": "Everett, WA",
      "country": "United States",
      "founded": 2013,
      "website": "https://www.helionenergy.com",
      "totalRaised": 1000000000,
      "valuation": null,
      "employees": "201-500",
      "lastRound": {
        "stage": "Series E",
        "amount": 500000000,
        "date": "2021-11",
        "leadInvestors": [
          "Sam Altman"
        ]
      },
      "notableInvestors": [
        "Sam Altman",
        "Mithril Capital",
        "Capricorn"
      ],
      "tags": [
        "fusion energy",
        "power"
      ],
      "momentumScore": 39.6
    },
    {
      "id": "form-energy",
      "name": "Form Energy",
      "description": "Grid-storage company developing long-duration iron-air batteries for multi-day renewable backup.",
      "sector": "sector-climate",
      "stage": "stage-growth",
      "headquarters": "Somerville, MA",
      "country": "United States",
      "founded": 2017,
      "website": "https://formenergy.com",
      "totalRaised": 1200000000,
      "valuation": null,
      "employees": "501-1,000",
      "lastRound": {
        "stage": "Series F",
        "amount": 405000000,
        "date": "2024-10",
        "leadInvestors": [
          "T. Rowe Price"
        ]
      },
      "notableInvestors": [
        "Breakthrough Energy",
        "ArcelorMittal",
        "TPG Rise"
      ],
      "tags": [
        "iron-air batteries",
        "grid storage"
      ],
      "momentumScore": 51.9
    }
  ],
  "sectors": [
    {
      "key": "sector-ai",
      "label": "AI & ML",
      "kind": "sector",
      "startupIds": [
        "openai",
        "anthropic",
        "xai",
        "mistral-ai",
        "perplexity",
        "scale-ai",
        "cohere",
        "hugging-face",
        "sierra",
        "skild-ai"
      ],
      "startupCount": 10,
      "totalRaised": 108650000000,
      "totalValuation": 456500000000,
      "topStartupId": "openai"
    },
    {
      "key": "sector-fintech",
      "label": "Fintech",
      "kind": "sector",
      "startupIds": [
        "stripe",
        "revolut",
        "ramp",
        "plaid",
        "brex"
      ],
      "startupCount": 5,
      "totalRaised": 15634000000,
      "totalValuation": 146400000000,
      "topStartupId": "plaid"
    },
    {
      "key": "sector-devtools",
      "label": "Dev Tools & Infra",
      "kind": "sector",
      "startupIds": [
        "databricks",
        "vercel",
        "anysphere"
      ],
      "startupCount": 3,
      "totalRaised": 15563000000,
      "totalValuation": 75150000000,
      "topStartupId": "anysphere"
    },
    {
      "key": "sector-saas",
      "label": "SaaS & Productivity",
      "kind": "sector",
      "startupIds": [
        "canva",
        "rippling",
        "notion",
        "deel"
      ],
      "startupCount": 4,
      "totalRaised": 3303000000,
      "totalValuation": 70900000000,
      "topStartupId": "rippling"
    },
    {
      "key": "sector-defense",
      "label": "Defense & Space",
      "kind": "sector",
      "startupIds": [
        "spacex",
        "anduril",
        "helsing"
      ],
      "startupCount": 3,
      "totalRaised": 14570000000,
      "totalValuation": 383400000000,
      "topStartupId": "spacex"
    },
    {
      "key": "sector-climate",
      "label": "Climate & Energy",
      "kind": "sector",
      "startupIds": [
        "commonwealth-fusion",
        "helion-energy",
        "form-energy"
      ],
      "startupCount": 3,
      "totalRaised": 4200000000,
      "totalValuation": 0,
      "topStartupId": "form-energy"
    }
  ],
  "stages": [
    {
      "key": "stage-late",
      "label": "Late stage",
      "kind": "stage",
      "startupIds": [
        "openai",
        "anthropic",
        "xai",
        "scale-ai",
        "stripe",
        "revolut",
        "databricks",
        "canva",
        "rippling",
        "spacex",
        "anduril"
      ],
      "startupCount": 11,
      "totalRaised": 145980000000,
      "totalValuation": 1029100000000,
      "topStartupId": "openai"
    },
    {
      "key": "stage-growth",
      "label": "Growth (C–E)",
      "kind": "stage",
      "startupIds": [
        "mistral-ai",
        "perplexity",
        "cohere",
        "hugging-face",
        "ramp",
        "plaid",
        "brex",
        "vercel",
        "anysphere",
        "notion",
        "deel",
        "helsing",
        "commonwealth-fusion",
        "helion-energy",
        "form-energy"
      ],
      "startupCount": 15,
      "totalRaised": 15355000000,
      "totalValuation": 97250000000,
      "topStartupId": "anysphere"
    },
    {
      "key": "stage-early",
      "label": "Early (Seed–B)",
      "kind": "stage",
      "startupIds": [
        "sierra",
        "skild-ai"
      ],
      "startupCount": 2,
      "totalRaised": 585000000,
      "totalValuation": 6000000000,
      "topStartupId": "sierra"
    }
  ],
  "totals": {
    "startups": 28,
    "sectors": 6,
    "stages": 3,
    "totalRaised": 161920000000,
    "totalValuation": 1132350000000,
    "unicornCount": 25
  }
};
